### ISSUE TITLE
Got "MDX compilation failed for generated file"

### ISSUE THREAD

**Issue by tulu1688** [PaloAltoNetworks/docusaurus-openapi-docs#1008]
## Describe the bug

Hello I create a sample of new empty Docusaurus project with command
```
npx create-docusaurus@latest my-website classic
```
The docusaurus dependencies after install are: 
```
    "@docusaurus/core": "3.5.2",
    "@docusaurus/preset-classic": "3.5.2",
```

I add `docusaurus-openapi-docs` library, and compile my new swagger file into `docs` folder.
Here are the openapi-docs versions:
```
    "docusaurus-plugin-openapi-docs": "^2.2.4",
    "docusaurus-preset-openapi": "^0.7.5",
    "docusaurus-theme-openapi-docs": "^2.2.4",
```

The config of plugins here, in `docusaurus.config.js`:
```
      [
        'docusaurus-plugin-openapi-docs',
        {
          docsPluginId: 'api',
          id: "api",
          config: {
            dbaas: {
              specPath: "swagger/dbaas.yaml",
              outputDir: "docs/api/dbaas",
              sidebarOptions: {
                groupPathsBy: "tagGroup",
              },
            },
          }
        },
      ]
```

And then I generate document files via:
```
yarn docusaurus gen-api-docs all
```

## Current behavior
After generate all documents, I have faced the error when compiling the project due to MDX file error.
```
Error: MDX compilation failed for file "/home/{username}/utils/test/docs/api/dbaas/list-articles.api.mdx"
Cause: Expected a closing tag for `<div>` (37:754-37:759) before the end of `paragraph`
```
another error
```
Module not found: Error: Can't resolve '@theme/ApiLogo' in '/home/{username}/utils/test/docs/api/dbaas'
--------------------------
Module not found: Error: Can't resolve '@theme/SchemaTabs' in '/home/{username}/utils/test/docs/api/dbaas'
--------------------------
Module not found: Error: Can't resolve '@theme/ApiExplorer/Export' in '/home/{username}/utils/test/docs/api/dbaas'
--------------------------
```

Here is the image of error 
![img](https://kailab.fun/minio/public/241031_dosaurus_openapi_bug.png)

## Your Environment

- Version used: ^2.2.4
- Environment name and version (e.g. Chrome 59, node.js 5.4, python 3.7.3):
- Operating System and version (desktop or mobile):
- Link to your project: https://github.com/tulu1688/docusaurus-api-docs

**Comment by aamir1995** [comment]
Use the following versions:
```
"docusaurus-plugin-openapi-docs": "^4.1.0",
"docusaurus-theme-openapi-docs": "^4.1.0",
```

**Comment by tulu1688** [comment]
Thanks @aamir1995 , I update the plugin and still get this error

```
  "devDependencies": {
    "@docusaurus/module-type-aliases": "3.5.2",
    "@docusaurus/types": "3.5.2",
    "docusaurus-plugin-openapi-docs": "^4.1.0",
    "docusaurus-theme-openapi-docs": "^4.1.0"
  },
```

![bug](https://kailab.fun/minio/public/241031_dosaurus_openapi_bug_01.png)

**Comment by tulu1688** [comment]
I resolve the issue by adding theme in `docusaurus.config.js`

```
    themes: ["docusaurus-theme-openapi-docs"],
```
