### ISSUE TITLE
"Unsupported pseudo class or element: global" warning when building site

### ISSUE THREAD

**Issue by johnmcase** [PaloAltoNetworks/docusaurus-openapi-docs#1021]
## Describe the bug

Warning written to build output when building my docusaurus site:

`[WARNING] {"message":"  ⚠ Unsupported pseudo class or element: global at assets/css/styles.035bba7f.css:8451:32111\n","compilerPath":"client"}`

## Expected behavior

Site builds without warnings

## Current behavior

Warning above is written to the console

## Possible solution

I'm pretty sure this is caused by the `:global` selector in https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/blob/c074d3fecc98a85b58ec04fa9b61529aee0f15ac/packages/docusaurus-theme-openapi-docs/src/theme/ApiExplorer/ApiCodeBlock/Line/_Line.scss#L39

Not sure what the fix would be.  Perhaps rename it to `_Line.module.scss`?

## Steps to reproduce

1.  Docusaurus 3.6.1  (was happening with 3.6.0 as well)
2.  docusaurus-openapi-docs 4.2.0  (was happening with 4.1.0 as well)
3.  My site is using `docusaurus-plugin-sass` 0.2.5 (latest), not sure if that matters
4.  npm run build

## Screenshots

![image](https://github.com/user-attachments/assets/f1a6e801-3d2f-4ab6-a3cc-66d4fd215e1a)

## Your Environment

- Docusaurus 3.6.1  (was happening with 3.6.0 as well)
- docusaurus-openapi-docs 4.2.0  (was happening with 4.1.0 as well)
- node 20.9.0
- npm 10.2.5
- git-bash on Windows 11

**Comment by blindaa121** [comment]
Issue resolved in https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/pull/1031
