### ISSUE TITLE
Multiple custom code samples for the same language / TypeScript support

### ISSUE THREAD

**Issue by m-murasovs** [PaloAltoNetworks/docusaurus-openapi-docs#1035]
### What I'm trying to achieve:

I want to add code examples that use both our JavaScript API client and the TypeScript clients using the `x-codeSamples` approach.

### The issue

Since there's no TS support for now (is there a plan to add this btw?), I wanted to add multiple examples, just like there are for each language by default (e.g. JavaScript has Fetch, jQuery, and XHR), but I haven't been able to find a way that works.

### The question 

Is it possible to add multiple code snippets using `x-codeSamples`?

Thanks in advance!

**Comment by sserrata** [comment]
Hi @m-murasovs, yes `x-codeSamples` are supported. Please refer to the demo for a live example. See #1036 for additional discussion on this topic.
