### ISSUE TITLE
Compiled OpenAPI files are not showing

### ISSUE THREAD

**Issue by eo33** [PaloAltoNetworks/docusaurus-openapi-docs#1037]
## Describe the bug

The generated .mdx files are not displayed properly. I was able to run `yarn docusaurus gen-api-docs all` and it generated the .mdx files in my folder. But when I run docusaurus and navigated to the .mdx page, I get this error:

![image](https://github.com/user-attachments/assets/24708bf1-3ff6-4c85-8ac3-30ad596b7d39)

I suspect that I'm not configuring the plugins in my config file correctly, even though I've followed the steps in the README. This is what my config file looks like:

```javascript
  plugins: [
    [
      "docusaurus-plugin-openapi-docs",
      {
        id: "api", // plugin id
        docsPluginId: "classic", // configured for preset-classic
        config: {
          account: {
            specPath: "oas/account.yaml",
            outputDir: "docs/account",
          },
        },
      },
    ],
  ],

  themes: ["docusaurus-theme-openapi-docs"],
```

## Expected behavior

The OpenAPI specifications being rendered beautifully in Docusaurus site. 

## Current behavior

I'm getting this error. 

## Steps to reproduce

1. Add an OAS file to a folder.
2. Add this code to the config file:
```javascript
...
  plugins: [
    [
      "docusaurus-plugin-openapi-docs",
      {
        id: "api", // plugin id
        docsPluginId: "classic", // configured for preset-classic
        config: {
          account: {
            specPath: "oas/account.yaml",
            outputDir: "docs/account",
          },
        },
      },
    ],
  ],
  themes: ["docusaurus-theme-openapi-docs"]
  ...
```
3. Generate the `.mdx` files using ` yarn docusaurus gen-api-docs all`
4. Run the site using `yarn start`
5. Navigate to the OpenAPI specs and you will get an error

## Context

I'm trying to show my API documentation. I have the OpenAPI specification ready, and just need a tool to help me render it. 

- Link to your project: https://github.com/eo33/oas_docu

**Comment by sserrata** [comment]
Hi @eo33, the presence of both a `package-lock.json` and `yarn.lock` tells me you likely have a dependency issue. I recommend deleting both lock files, along with `node_modules` and performing a fresh install of dependencies using either `npm` or `yarn`.
