### ISSUE TITLE
No 'authorize' button or any other way to authenticate a request?

### ISSUE THREAD

**Issue by avivace** [PaloAltoNetworks/docusaurus-openapi-docs#1038]
Hi, I'm evaluating the plugin for a development of an "API playground"-like experience but I found that you removed the 'Authorize' button. I only saw this comment regarding it https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/issues/150#issuecomment-1180828656, mentioning:

> FWIW, for security reasons, this project intentionally removed the authentication form and ability to send requests from the browser. We determined that storing credentials in the browser is a dangerous practice that should be avoided, since it potentially exposes those credentials to XSS/XSR and similar attacks.

Do you have any suggested approach/official statement regarding the possibility of authenticating a request ? Or this has definitely dropped and only public/non-authenticated APIs are "in scope"?

**Comment by sserrata** [comment]
Hi @avivace, please explore our live demo for examples - the "AUTHORIZE" button was refactored a while back into the request form. Basically, when security schemes are defined the API key/token or password inputs become available in the request form.

**Comment by avivace** [comment]
> Hi @avivace, please explore our live demo for examples - the "AUTHORIZE" button was refactored a while back into the request form. Basically, when security schemes are defined the API key/token or password inputs become available in the request form.

Thanks @sserrata you're indeed right!
