### ISSUE TITLE
Swizzle ParamsItem results in compile errors

### ISSUE THREAD

**Issue by tyler-mairose-sp** [PaloAltoNetworks/docusaurus-openapi-docs#1047]
## Describe the bug

When I swizzle the `ParamsItem` component from `docusaurus-theme-openapi-docs`, I receive the following error:

```
× Module parse failed:
  ╰─▶   × JavaScript parsing error: Expected ',', got ':'
          ╭─[8:45]
        6 │  * ========================================================================== */
        7 │
        8 │ export function createDescription(description: string | undefined) {
          ·                                              ─
        9 │   if (!description) {
       10 │     return "";
          ╰────
      
  help: 
        You may need an appropriate loader to handle this file type.

--------------------------

× Module parse failed:
  ╰─▶   × JavaScript parsing error: Expected ',', got ':'
          ╭─[10:26]
        8 │ import { SchemaObject } from "../types";
        9 │
       10 │ function prettyName(schema: SchemaObject, circular?: boolean) {
          ·                           ─
       11 │   if (schema.format) {
       12 │     return schema.format;
          ╰────
      
  help: 
        You may need an appropriate loader to handle this file type.

--------------------------

× Module parse failed:
  ╰─▶   × JavaScript parsing error: Expected '{', got 'type'
          ╭─[11:7]
        9 │
       10 │ /** @deprecated use ReactNode from React instead */
       11 │ export type Children = ReactNode;
          ·        ────
       12 │
       13 │ export type Props = Record<string, any> & { children?: ReactNode };
          ╰────
      
  help: 
        You may need an appropriate loader to handle this file type.
```

## Expected behavior

I would expect the swizzle to compile normally so that I can add my custom code. I wish to add a custom link under the existing details.

![image](https://github.com/user-attachments/assets/84dfa8a4-3596-4521-9990-c02166723c45)

## Current behavior

I get the error I provided above.

## Steps to reproduce

1. Swizzle `ParamsItem` component from `docusaurus-theme-openapi-docs`

## Your Environment

- Version used: Docusaurus 3.6.1, docusaurus-openapi-docs canary 0.0.0-949
- Environment name and version (e.g. Chrome 59, node.js 5.4, python 3.7.3): Chrome Version 131.0.6778.109 
- Operating System and version (desktop or mobile): MacOS
- Link to your project: https://github.com/sailpoint-oss/developer.sailpoint.com

**Comment by sserrata** [comment]
Hi @tyler-mairose-sp, sorry but `swizzle` is a docusaurus feature and, in looking at the errors you're seeing, it appears you may have an issue with your node/development environment.
