### ISSUE TITLE
[FR] Support Parent Tag Grouping

### ISSUE THREAD

**Issue by csestito** [PaloAltoNetworks/docusaurus-openapi-docs#142]
### Is your feature request related to a problem?

No

### Describe the solution you'd like

Today, we can group by tag for multiple spec files within the same directory. It would be nice to have the ability to group a set of those spec files together in one parent category instead of having to define separate APIs in the config.  

##### The idea: 
Add a `x-parent-category` option to the spec file(s) that includes a Summary (display in the sidebar) . With that option, a sidebar category would be created and the items of that sidebar category would be a concatenation of the sidebar categories for each tag in each spec file that shares the `x-parent-category`. 

A simplified example: 

I have spec files for my shop named Apple, Banana, Double Shot, Latte, Cortado . In Apple, all endpoints are tagged `Apple`, in Banana all are tagged `Banana`, etc... I would create a `x-parent-category`: "Fruits" which would be added to the Apple and Banana spec files. The generated Sidebar would then have a top level category: Fruits with items that is an array of the Apple sidebar category and Banana sidebar category. The same thing would happen for `x-parent-category` of Espresso Drinks

We'd See on the sidebar: 
Fruits ▼
> Apple ▼
- buy apple
- clean apple
- eat apple

> Banana ▼
- buy banana
- clean banana
- eat banana

Espresso Drinks ▼
> Double Shot ▼
- buy double shot
- drink double shot

> Double Shot ▼
- buy latte
- drink latte

> Cortado ▼
- buy cortado
- drink cortado

The main difference between what is there today would be that if `x-parent-category` was specified the generated sidebar would add the higher level category. If no `x-parent-category` is specified, there would be no difference in the output.

**Comment by sserrata** [comment]
Thanks @csestito! 

Have you considered perhaps going a step further to define Docusaurus vendor extensions? Also, perhaps we could swap `parent` with `root` (since it would be the top-most category)?

For example:

* `x-docusaurus-root-category` _string_
* `x-docusaurus-root-category-description` _string_ (could also contain MDX/MD)

> Note that the description could be rendered as the `categoryLinkSource` along with the generated index

**Comment by csestito** [comment]
Update: Not going to fix this use case. 

The parent grouping/groubBySpec is accomplishable with proper tagging and division of the spec files. This is a narrow use case and shouldn't cause us to rewrite the logic. It is best to keep the base groupByTags and allow the user to organize their specs or customize the sidebar in a way they'd like it to display. 

If you'd like to group spec files together, put them in a directory together and use the sidebar to create the top level categories. If you'd like to group by spec file, make sure the spec file has all operations tagged with the same tag first in their tag array. 

In the future we can look into grouping tags together, but for now it is best to leave it as is.
