### ISSUE TITLE
Error on Docusaurus 2.0.0-rc.1

### ISSUE THREAD

**Issue by homotechsual** [PaloAltoNetworks/docusaurus-openapi-docs#161]
## Describe the bug

> This page crashed.
> Hook useTabGroupChoice is called outside the <TabGroupChoiceProvider>.

## Expected behavior

Page should load.

## Current behavior

Page crashes with above message.

## Steps to reproduce

Docusaurus 2.0.0-rc.1, Open API 0.0.0-396

Have cleared and rebuilt API documentation using 396 canary.

**Comment by homotechsual** [comment]
Self-inflicted. Don't abuse undocumented config options and expect things to work :-D

**Comment by homotechsual** [comment]
Nope, issue still present after removing `languageTabs` config item.

**Comment by sradu** [comment]
I'm getting the same error in rc1.

**Comment by sserrata** [comment]
Thanks @homotechsual and @sradu, we haven't upgraded the plugin/theme to support `rc.1` yet but will try to get to it this week. Until then, we recommend sticking with the supported Docusaurus version(s):

![image](https://user-images.githubusercontent.com/9343811/179530500-993d0d4c-dfa6-47e6-b1b7-7f5cce5a8a88.png)

**Comment by sserrata** [comment]
Issue also referenced in #162

**Comment by sserrata** [comment]
Support for 2.0.0-rc.1 introduced in v1.1.1
