### ISSUE TITLE
Module not found: Error: Can't resolve '@theme/DocItemFooter'

### ISSUE THREAD

**Issue by sradu** [PaloAltoNetworks/docusaurus-openapi-docs#162]
## Describe the bug

I'm using Docusaurus 2.0.0-rc.1 and getting this error:

Module not found: Error: Can't resolve '@theme/DocItemFooter' in node_modules/docusaurus-theme-openapi-docs/lib-next/theme/ApiItem'.

My plugin section looks like this:
```
      '@docusaurus/plugin-content-docs',
      {
        path: 'docs/api/petstore',
        routeBasePath: '/api/petstore',
        id: 'apiPetstore',
        sidebarPath: require.resolve('./sidebars/petstore.js'),
        sidebarCollapsible: false,
        docLayoutComponent: "@theme/DocPage",
        docItemComponent: "@theme/ApiItem",
      },
    ],
```

Thanks!

**Comment by thomasheartman** [comment]
@sserrata This may well be me doing something wrong, but I'm seeing the same error with Docusaurus 2.0.0-beta.22. 

Seeing that this package doesn't support rc.1 yet, I decided to try and downgrade to beta.22 (by updating package.json and regenerating the lockfile). However, the error persists. Could it be that this specific one isn't an rc.1 issue? It's also quite possible that I've messed something up when trying to downgrade. Do you have any ideas as to what that might have been in that case? 

Thanks for the package and your attention, by the way! It looks great and I'm looking forward to integrating it 😄

**Comment by sserrata** [comment]
Hi @thomasheartman, thanks for sharing your issue. What version of the `docusaurus-openapi-docs` plugin/theme are you seeing it in?

**Comment by thomasheartman** [comment]
Hi, @sserrata! Thanks for the response 😄 Ah, okay, that makes sense about the version. Yeah, it was v1.0.6. I see you've released a v1.1.0 now, so I'll give it a go with that and see if it works out any better.

**Comment by Ahmad-anility** [comment]
Hi @sserrata and @thomasheartman I just tested version 1.1.0` and the dependency issue is fixed  👍

**Comment by Ahmad-anility** [comment]
But now when I clean the api docs and generate them again I get 
```
Docusaurus server-side rendering could not render static page with path ...
```

**Comment by sserrata** [comment]
Hi @Ahmad-anility, can you share your `package.json` dependencies? My first thought is that there could be a mismatch on theme dependencies. What version of Docusaurus are you testing with?

**Comment by Ahmad-anility** [comment]
Apologies @sserrata, it must have been my node_module folder. After removing and installing again, it works now. 
Also sharing the `package.json`:

`package.json` dependency is 

```
  "dependencies": {
    "@docusaurus/core": "^2.0.0-rc.1",
    "@docusaurus/preset-classic": "^2.0.0-rc.1",
    "@mdx-js/react": "^1.6.22",
    "clsx": "^1.1.1",
    "docusaurus-plugin-openapi-docs": "^1.1.1",
    "docusaurus-theme-openapi-docs": "^1.1.1",
    "prism-react-renderer": "^1.3.3",
    "react": "^17.0.2",
    "react-dom": "^17.0.2"
  },
  "devDependencies": {
    "@docusaurus/module-type-aliases": "^2.0.0-rc.1"
  },

```

**Comment by sserrata** [comment]
Support for 2.0.0-rc.1 introduced in v1.1.1
