### ISSUE TITLE
[FR] Ability to setup header for Json Request Body Example

### ISSUE THREAD

**Issue by johnnyswan** [PaloAltoNetworks/docusaurus-openapi-docs#193]
### Is your feature request related to a problem?

Our server works with a specific `application/vnd.api+json` header. And because of that we have no way to show our users a sample request body, because the library only handles `application/json`.

`/packages/docusaurus-plugin-openapi-docs/src/openapi/openapi.ts:172`
<img width="807" alt="image" src="https://user-images.githubusercontent.com/11737164/183074229-a7942cb6-0334-4120-9fd2-14837118dc7e.png">

### Describe the solution you'd like

I want to offer the possibility to customize which headers will be used for `requestBody` via plugin settings or something like that.

### Describe alternatives you've considered

n/a

### Additional context

Structure example:
<img width="804" alt="image" src="https://user-images.githubusercontent.com/11737164/183074116-a20906cf-ca2d-4130-803c-e37562ae1e3f.png">

**Comment by sserrata** [comment]
Hi @johnnyswan, thanks for the feature request. 

Expanding MIME support for both request and response is something we've discussed internally. My initial thought it that maybe we can find a way to detect/iterate through all available MIME types and give readers the option to choose which one to view. If we repurpose the `Tabs` component for this, it's possible we could even persist the user's choice in `localStorage` so it's automatically chosen throughout the documentation.

**Comment by johnnyswan** [comment]
@sserrata How can I help you with this? Maybe you have some ideas or discussions so I can work with this and make a merge request

**Comment by sserrata** [comment]
Thanks! Would it be possible to get a copy of the OpenAPI spec with the vendor MIME type (or an example)? I'm mainly interested in seeing if it's more or less compatible with our `createSchemaDetails` function.

**Comment by johnnyswan** [comment]
You can find it [here](https://github.com/Trisk-io/documentation/blob/main/openapi/openapi.json)

**Comment by sserrata** [comment]
Thanks! I might have a PR for you to preview soon. Will keep you posted.

**Comment by sserrata** [comment]
Hi @johnnyswan, PR #195 is currently opened. Would like to get your feedback on whether or not it addresses the issues you were having. The UI/UX is not final but the solution appears to work, no matter what MIME type is presented. Thanks!

Here's a demo:

https://user-images.githubusercontent.com/9343811/183216849-6af529db-1778-4cbd-908a-77987293d099.mov

**Comment by johnnyswan** [comment]
It's a good idea to show Tabs with MIME type selection. But we also need to fix the `Body` component that used in the `ApiDemoPanel` component. In the video that you provided you can see that this component is empty.

**Comment by TarasMelnyk** [comment]
@sserrata Do you have a plan for fixing an issue that Johnny described? I mean, with an empty body, in the right block of the example
<img width="1483" alt="Снимок экрана 2022-08-09 в 13 52 07" src="https://user-images.githubusercontent.com/14990870/183640758-06e4c86a-a119-4d60-b538-a57bb5818999.png">

**Comment by sserrata** [comment]
Hi @TarasMelnyk, yes, there's a fix on the way. Hopefully will be ready to merge today.

**Comment by sserrata** [comment]
Making some progress...

https://user-images.githubusercontent.com/9343811/183656898-df5dbaf0-735b-45e9-844d-ec0fd1fb464c.mov

**Comment by TarasMelnyk** [comment]
I appreciate your work on this

**Comment by sserrata** [comment]
Canary release `0.0.0-418` has been published, with support for multiple content/mime types. Interested to hear your feedback on how well it works for you. Thanks!

**Comment by johnnyswan** [comment]
Thanks. It works perfectly. I think it's a great solution because the user will always have information about the necessary header

**Comment by TarasMelnyk** [comment]
The solution for a body works very well. But I found some regression, we update to `0.0.0-418`, and all parameters in the request and response bodies now are marked as required but in the openapi file it does not have a "required" attribute and before the update, they were not marked as required
<img width="1417" alt="0 0 0-418" src="https://user-images.githubusercontent.com/14990870/183853529-949bdf94-ebb9-4ff6-881f-45abdc3106b0.png">
<img width="1466" alt="Before update" src="https://user-images.githubusercontent.com/14990870/183853542-3d97eef1-f6b8-485b-adab-4adcb7a286f4.png">
<img width="950" alt="OpenAPI" src="https://user-images.githubusercontent.com/14990870/183853548-c89f6e4e-d4a1-4491-afd0-30a3d4de21c6.png">

**Comment by sserrata** [comment]
Thanks @TarasMelnyk, I was able to isolate the bug and opened #198 to address it. Going to do a bit more testing before merging but I appreciate any help. You should be able to pull the PR branch, run `yarn build-packages` and use the demo to test with your OpenAPI spec. Let me know if you have any questions. Thanks!

**Comment by sserrata** [comment]
In my quick test it appears to be back to the way it was before the update:

<img width="1377" alt="Screen Shot 2022-08-10 at 10 12 49 AM" src="https://user-images.githubusercontent.com/9343811/183923402-75f552c3-ce7d-4975-930d-9b8bd9406c69.png">

**Comment by sserrata** [comment]
Here's a new canary release to test with: `0.0.0-419`
