### ISSUE TITLE
How to run gen-api-docs with npm instead of yarn?

### ISSUE THREAD

**Issue by alexandrehtrb** [PaloAltoNetworks/docusaurus-openapi-docs#204]
## Documentation link

[README.md](https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/blob/main/README.md)

## Describe the problem

Hello,

This is a noob question, but how do I run the `gen-api-docs` commands with npm instead of yarn? The documentation is entirely yarn-based.
For example, what would be the equivalent command with npm?
`yarn docusaurus gen-api-docs all`

## Suggested fix

Provide commands examples using npm.

**Comment by sserrata** [comment]
Hi @alexandrehtrb, have you tried `npm run docusaurus gen-api-docs all`?

**Comment by alexandrehtrb** [comment]
`npm run` worked, thank you!
