### ISSUE TITLE
Response examples are not appearing

### ISSUE THREAD

**Issue by alexandrehtrb** [PaloAltoNetworks/docusaurus-openapi-docs#205]
## Describe the bug

Response examples are not appearing for a request; they do appear when I preview my OpenApi in [Swagger Editor](https://editor.swagger.io/).
(I presume this feature is available, I searched and found the PR #176 ).

## Expected behavior

A response example like the one below should show up:

![image](https://user-images.githubusercontent.com/27026741/184197852-70b46f8c-4f58-48b9-8187-b05747b9af84.png)

## Current behavior

My response example does not show:

![image](https://user-images.githubusercontent.com/27026741/184198211-be535dea-dd48-40a9-8e2d-c88d9268aba7.png)

## Steps to reproduce

My API config in `docusaurus.config.js` plugin section:

```js
api_shoppinglist: { 
  specPath: "openapis/swagger_shoppinglist.yaml",
  outputDir: "docs/api_shoppinglist",
  sidebarOptions: {
    groupPathsBy: "tag",
    categoryLinkSource: "tag",
    sidebarCollapsible: true,
    sidebarCollapsed: false
  }
}
```

My OpenAPI file is available at: https://pastebin.com/n0n4dTu7

## Your Environment

- Docusaurus version used: v2.0.1
- Docusaurus OpenAPI Docs version used: v1.1.4
- Environment name and version: Node.js v16.16
- Operating System and version (desktop or mobile): Windows 10 x64

**Comment by sserrata** [comment]
Thanks for reporting @alexandrehtrb. There are a number of bug fixes coming in v1.1.5 that should address your issue. Can you test using canary release `0.0.0-422` and let me know if it works?

**Comment by sserrata** [comment]
I was able to reproduce the issue you are seeing. I'll need to check with @blindaa121 to see what the issue might be.

**Comment by sserrata** [comment]
Hmmm, I think I figured it out...it appears we were only checking for `examples` and not `example`, which is also supported.

https://user-images.githubusercontent.com/9343811/184216656-2dff0a76-1ac8-4485-ad4a-ac9ae5223178.mov

**Comment by sserrata** [comment]
Please install `0.0.0-423` and let me know if it resolves your issue. Thanks!

**Comment by alexandrehtrb** [comment]
I tried the new version and the result was the same as in your video.
Is it possible to have the layout like in the video of the PR #176 ? I liked that design.

I also started to have an error in another OpenApi documentation, here is the stack trace:
```
[ERROR] TypeError: Cannot read properties of null (reading 'value')
    at C:\PROJETOS\TesteDocusaurus\my-website\node_modules\docusaurus-plugin-openapi-docs\lib\markdown\createStatusCodes.js:66:72
    at Array.map (<anonymous>)
    at createResponseExamples (C:\PROJETOS\TesteDocusaurus\my-website\node_modules\docusaurus-plugin-openapi-docs\lib\markdown\createStatusCodes.js:57:45)
    at C:\PROJETOS\TesteDocusaurus\my-website\node_modules\docusaurus-plugin-openapi-docs\lib\markdown\createStatusCodes.js:129:37
    at guard (C:\PROJETOS\TesteDocusaurus\my-website\node_modules\docusaurus-plugin-openapi-docs\lib\markdown\utils.js:21:26)
    at C:\PROJETOS\TesteDocusaurus\my-website\node_modules\docusaurus-plugin-openapi-docs\lib\markdown\createStatusCodes.js:97:47
    at Array.map (<anonymous>)
    at createStatusCodes (C:\PROJETOS\TesteDocusaurus\my-website\node_modules\docusaurus-plugin-openapi-docs\lib\markdown\createStatusCodes.js:83:33)
    at createApiPageMD (C:\PROJETOS\TesteDocusaurus\my-website\node_modules\docusaurus-plugin-openapi-docs\lib\markdown\index.js:44:51)
    at C:\PROJETOS\TesteDocusaurus\my-website\node_modules\docusaurus-plugin-openapi-docs\lib\index.js:168:54
```

(I cannot share this OpenApi right now, I will see if I can remove the sensitive parts)

**Comment by sserrata** [comment]
Can you share only your response example(s)?

**Comment by alexandrehtrb** [comment]
> Can you share only your response example(s)?

I believe it was this response:

```yaml
responses:
  '201':
    description: A solicitação com o seu status.
    content:
      application/json:
        schema:
          $ref: '#/components/schemas/AfvafafafResult'
        example:
          id: 45df45a7-a87f-46f1-a632-17f414e051f0
          tipo: ZgfaysfJsfkafa
          status: Sfhfahajsfha
          ff1: 0
          ff2: 0
          konuln: null
          fififi:
            nomeIfjasghfkajhsfa: NAME LASTNAME
            vadasa:
              nome: NAME LASTNAME
              documento: 11.111.111/0001-00
            dedede:
              nome: NAME LASTNAME
              documento: 11.111.111/0001-00
            permiteAkfoafkoaf: false
            valorMin: 180.5
            valorMax: 180.5
            dataMaxUtc: '0001-01-01T00:00:00+00:00'
            moeda: BRL
            valor: 180.5
            dataWfuifaUtc: '2021-04-24T16:55:27.193Z'
            dataOfoaifaUtc: '2021-04-23T16:55:27.193Z'
            mofafmoasfa: '11111111111111111111111111111111111111111111111'
          erro: null
          datauiDwUtc: '2021-04-23T16:55:27.196Z'
```

**Comment by sserrata** [comment]
Thanks! I will work on reproducing. By the way...can you share specifically what about the #176 video you would like?

**Comment by alexandrehtrb** [comment]
I liked it more, for being a single example:
![image](https://user-images.githubusercontent.com/27026741/184242286-b9b7fbbf-de4d-49f2-ad45-520563970061.png)

In the Shopping List example, each field in the response example YAML became a different "response example" in the documentation page:

![image](https://user-images.githubusercontent.com/27026741/184242526-6cd6e497-fc5d-475f-b596-810f4112011b.png)

(Id, Title and Items are JSON fields of the original response example)

**Comment by sserrata** [comment]
I think I solved it.

Uploading Screen Recording 2022-08-11 at 5.12.14 PM.mov…

**Comment by alexandrehtrb** [comment]
I tried the latest version here and it is working nicely! Thanks!
