### ISSUE TITLE
The endpoint path is not displayed

### ISSUE THREAD

**Issue by akselleirv** [PaloAltoNetworks/docusaurus-openapi-docs#214]
## Describe the problem

When I generate the `.mdx` files based on my OpenAPI spec it does not display the path to the endpoint itself.

How can I do this?

**Comment by sserrata** [comment]
Hi @akselleirv, can you share your OpenAPI spec or a snippet/example of one of your paths? Thanks!

**Comment by sserrata** [comment]
@akselleirv any updates to share?
