### ISSUE TITLE
Response Example Not Visible

### ISSUE THREAD

**Issue by julianbirkett** [PaloAltoNetworks/docusaurus-openapi-docs#219]
## Describe the bug

Using your example Petstore OpenAPI spec I am not seeing the Example button to the right of the Schema button which I would expect. I have used another API spec with similar results.

## Expected behavior

I would expect the generated mdx file to have the details of the response example in it which would enable the Example button

## Current behavior

There is no code in the generated mdx about the response example from the open API spec

## Possible solution

I have not looked at the code but I suspect the example data is not being read correctly to be inserted into the mdx file. I notice you have made a fix to this recently and I did try an earlier version but it didn't improve things.

## Steps to reproduce

1. Add the plugin for the spec into the docusaurus.config.js

          id: "apiDocs",
          docsPluginId: "classic",
          config: {
            petstore: { // Note: petstore key is treated as the <id> and can be used to specify an API doc instance when using CLI commands
              specPath: "apidocs/petstore.yaml", // Path to designated spec file
              outputDir: "docs/apis/petstore", // Output directory for generated .mdx docs
              sidebarOptions: {
                groupPathsBy: "tag",
                categoryLinkSource: "tag",
                sidebarCollapsible: true,
                customProps: {},
              },
            }
2.  Add the entry into a sidebar somewhere

    {
      type: "category",
      label: "Petstore",
      link: {
        type: "generated-index",
        title: "Petstore API",
        description:
          "This is a sample server Petstore server. You can find out more about Swagger at http://swagger.io or on irc.freenode.net, #swagger. For this sample, you can use the api key special-key to test the authorization filters.",
        slug: "/category/petstore-api"
      },
      // @ts-ignore
      items: require("./docs/apis/petstore/sidebar.js")
    }

3. Or you can just use your open API example template https://github.com/PaloAltoNetworks/docusaurus-template-openapi-docs.git
4. Generate the mdx files with npm run gen-api-docs all
5. Run the site with npm run start
6. Navigate to the defined page via the sidebar and pick Pets, Find pet by ID
7. Look in the responses section and you will see The Schema button but no Example button

## Screenshots

![ExampleScreenShot](https://user-images.githubusercontent.com/22931256/185600598-b323cc2d-22aa-449a-8d08-26592e426fd9.jpg)

## Context

I see this as a fundamental part of your plugin as without it developers will find it hard to picture the data required

## Your Environment

- Version used: 1.1.8 and 1.1.5 before the last fix mentioning examples
- Environment name and version (e.g. Chrome 59, node.js 5.4, python 3.7.3): Chrome Version 104.0.5112.81 (Official Build) (64-bit)
- Desktop windows 10 PC running build 10.0.19044
- Link to your project: Your template project https://github.com/PaloAltoNetworks/docusaurus-template-openapi-docs.git

**Comment by sserrata** [comment]
Hi @julianbirkett, examples should only render if there is an example or examples key present under the operation. Otherwise only the schema should render.

**Comment by julianbirkett** [comment]
I think you're saying we have to have a whole example section in the spec and that you render from that? Most specs I've seen have the example against each property e.g. In petstore.yaml Pet schema, the 'name' property looks like this

        name:
          description: The name given to a pet
          type: string
          example: Guru

Therefore, the example data of Guru is defined with the property and there isn't a separate example key 

Would it be possible for you to give an example of what you mean please? 

Regards,

Julian

**Comment by sserrata** [comment]
Hi @julianbirkett, we do use the property-level `example` you're referencing when constructing an example _request_ body. For _response_ examples, we require an `example` or `examples` to be defined under the response `schema`. 

Request body examples (I included ReDoc for comparison):

OpenAPI Docs Plugin: https://docusaurus-openapi.tryingpan.dev/petstore/add-pet
ReDoc: https://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/PaloAltoNetworks/docusaurus-openapi-docs/main/demo/examples/petstore.yaml#tag/pet/operation/addPet

Response example:

OpenAPI Docs Plugin: https://docusaurus-openapi.tryingpan.dev/petstore/login-user
ReDoc: https://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/PaloAltoNetworks/docusaurus-openapi-docs/main/demo/examples/petstore.yaml#tag/user/operation/loginUser

**Comment by julianbirkett** [comment]
OK I understand where you're coming from and thanks for your help in explaining it. 

Just to let you know what you've described isn't my experience with other OpenAPI parsers as they use the examples at the property level to build their response examples. You just need to look at how these are constructed in the swagger.io UI and extensions for VS Code. I have attached the petstore example of GET /pet/{petId} from swagger hub where you can see the response is just the name because that was the only example added in the properties. In my opinion, having the separate example makes it very difficult to keep your examples in line with the API properties if a separate definition of the example has to be created in the definition file. That's because the object definition does not live in close proximity to the example and, therefore, it's really hard to keep them in line. I think this will prevent many people using your plugin and it doesn't feel compatible with Swagger 2.0 or Open API 3.x.

![SwaggerIOScreenShot](https://user-images.githubusercontent.com/22931256/185962217-d691cb38-fabf-463a-903b-f6a434ecad7d.jpg)

Regards, 
Julian

**Comment by sserrata** [comment]
Hi @julianbirkett, thanks for the feedback. 

As mentioned before, we already use a similar approach to build the request body. In theory, we should be able to apply this method to generate a response "Example" but it wouldn't be strictly based on the property-level `example`. For instance, in cases where a property doesn't have an `example` we could infer and display the type or generate an example value based on some predefined cases like `date-time`, `boolean`, etc. This appears to be what Swagger UI is doing.

>  In my opinion, having the separate example makes it very difficult to keep your examples in line with the API properties if a separate definition of the example has to be created in the definition file.

I hear what you're saying but schema-level example(s) are supported by OpenAPI and we see them used in some of our product API specs. That said, I think it would be entirely up to the user to decide which style of examples they wanted to use, i.e. schema example(s) vs property-level or inferred.

**Comment by julianbirkett** [comment]
Yes doing the same thing you do for the request example would work well and be in line with Swagger UI. It would also give people the option to choose. Do you think this is something that could be changed please?

Regards, Julian

**Comment by sserrata** [comment]
Still running tests but I think it should work.

https://user-images.githubusercontent.com/9343811/186010249-025ee77f-eb11-4fb7-9e80-d5d5b446631c.mov

**Comment by julianbirkett** [comment]
That’s excellent. Thank you very much

**Comment by sserrata** [comment]
Hi @julianbirkett, just published canary release `0.0.0-433`. Can you please install and check to see if it addresses your issue? Thanks!

**Comment by julianbirkett** [comment]
Yes @sserrata that looks to be working as expected now. Thanks Steven.
