### ISSUE TITLE
The Sidebar is not getting generated automatically

### ISSUE THREAD

**Issue by snehilms** [PaloAltoNetworks/docusaurus-openapi-docs#220]
## Describe the bug

On adding yaml's and generating the docs, the sidebars are not getting generated automatically, though the file is generated but with minimal boilerplate and not the api's with items and all.

## Expected behavior

The filled sidebar must be automatically generated on adding new yamls and updating the configuration in the docusaurus.config file

## Current behavior

The mdx files are generated but the autogeneration of the sidebar is not happening

## Steps to reproduce
This is my repo with the files added: 
https://github.com/snehilms/docusaurus-openapi-docs
You can clone this and do yarn build and yarn start
And check for the nftapi.yaml which i have added personally
## Screenshots
![image](https://user-images.githubusercontent.com/42109401/185647171-d5494f92-b2f8-4032-aefb-5138865ec600.png)

![image](https://user-images.githubusercontent.com/42109401/185647381-aad59011-c4b2-4129-bc9f-44b942b739ed.png)

- Link to your project: https://github.com/snehilms/docusaurus-openapi-docs

**Comment by sserrata** [comment]
Hi @snehilms, the sidebar categories are only created if the tags are defined at the root level of the spec. I recommend defining all tags at the root with the tag.name matching the tags under each operation. Then you may also add x-displayName to each tag to customize the category label. Let me know if this works.

**Comment by snehilms** [comment]
> Hi @snehilms, the sidebar categories are only created if the tags are defined at the root level of the spec. I recommend defining all tags at the root with the tag.name matching the tags under each operation. Then you may also add x-displayName to each tag to customize the category label. Let me know if this works.

I have the tags defined at the yaml specification file.

**Comment by snehilms** [comment]
> Hi @snehilms, the sidebar categories are only created if the tags are defined at the root level of the spec. I recommend defining all tags at the root with the tag.name matching the tags under each operation. Then you may also add x-displayName to each tag to customize the category label. Let me know if this works.

Yeah it works 
And one more thing what is the use of the x-tagGroups

**Comment by sserrata** [comment]
Nice! The x-tagGroups is a ReDoc vendor extension for defining what the sidebar hierarchy should be. We don't support it (yet) but are considering it as another way to generate the sidebar.
