### ISSUE TITLE
Try it Feature for getting the Responses

### ISSUE THREAD

**Issue by snehilms** [PaloAltoNetworks/docusaurus-openapi-docs#222]
We can have a Try it Button with the response being loaded by hitting the actual api
It can be like the ones implemented by many documentations like:
![image](https://user-images.githubusercontent.com/42109401/185795776-82da3ea0-454a-4a32-b501-cd199ebd38e2.png)

**Comment by sserrata** [comment]
Hi @snehilms, we are a cybersecurity company and decided to remove the "Try it" functionality for security reasons. 

The short explanation is that we believe it is too risky to allow users to share their API keys/tokens via the browser, at least not without having properly implemented an appropriate security scheme, e.g. OpenID + OAuth 2.0 (short lived tokens). 

We recognize the convenience of sending API requests from the browser but believe it's not much more effort to copy and paste a code snippet into a shell or vscode. Alternatively, users may use tools like Insomnia or Postman which, IMO, provide a much more robust solutions for this use case.

Definitely open to feedback or ideas for how to enable this functionality with user safety in mind. Thanks!
