### ISSUE TITLE
[FR] Show tag description in DocCategoryGeneratedIndexPageContent

### ISSUE THREAD

**Issue by sradu** [PaloAltoNetworks/docusaurus-openapi-docs#230]
### Is your feature request related to a problem?

Tags can have descriptions. If a description would be provided to DocCategoryGeneratedIndexPageContent it would be shown.

```
  "tags": [
    {
      "name": "Baking",
      "description": "This module offers operations dealing with baking."
    }
  ],
```

### Describe the solution you'd like

For the DocCategoryGeneratedIndexPageContent to show the description provided in the spec.

**Comment by sserrata** [comment]
Hi @sradu, have you tried setting the `categoryLinkSource` to "tag"?

https://docusaurus-openapi.tryingpan.dev/#sidebaroptions

**Comment by sradu** [comment]
@sserrata well that's embarrassing for me haha. That did the trick. Thank you sir!
