### ISSUE TITLE
Crashing docs due to useTabGroupChoice

### ISSUE THREAD

**Issue by calthejuggler** [PaloAltoNetworks/docusaurus-openapi-docs#237]
## Describe the bug

Any docs that would have code snippet tabs on them are crashing.

## Expected behavior

The page should load with the documentation and code snippets.

## Current behavior

For any page that would have code snippets, I receive an error saying:
```
This page crashed.
Hook useTabGroupChoice is called outside the <TabGroupChoiceProvider>.
```
and the console gives a `ReactContextError` and says it happened in the `<ApiTabsComponent>` and the `<TabsComponent>`.

## Steps to reproduce

1. Setup docusaurus with the following config:
```javascript
// @ts-check
// Note: type annotations allow type checking and IDEs autocompletion

const lightCodeTheme = require("prism-react-renderer/themes/github");
const darkCodeTheme = require("prism-react-renderer/themes/dracula");

/** @type {import('@docusaurus/types').Config} */
const config = {
  /* ... */
  presets: [
    [
      "classic",
      /** @type {import('@docusaurus/preset-classic').Options} */
      ({
        docs: {
          sidebarPath: require.resolve("./sidebars.js"),
          editUrl: "...",
          docLayoutComponent: "@theme/DocPage",
          docItemComponent: "@theme/ApiItem",
        },
        theme: {
          customCss: require.resolve("./src/scss/custom.scss"),
        },
      }),
    ],
  ],

  plugins: [
    "docusaurus-plugin-sass",
    [
      "docusaurus-plugin-openapi-docs",
      {
        id: "apiDocs",
        docsPluginId: "classic",
        config: {
          collector: {
            specPath: "spec.yaml", // Path to designated spec file
            outputDir: "docs/API", // Output directory for generated .mdx docs
            sidebarOptions: {},
          },
        },
      },
    ],
  ],

  themes: ["docusaurus-theme-openapi-docs"],

  themeConfig:
    /** @type {import('@docusaurus/preset-classic').ThemeConfig} */
    ({
      navbar: {
        title: "...",
        logo: {
          alt: "...",
          src: "img/logo.svg",
        },
        items: [
          {
            type: "doc",
            docId: "getting-started",
            position: "left",
            label: "Docs",
          },
        ],
      },
      footer: {
        style: "dark",
        links: [
          {
            title: "Docs",
            items: [
              {
                label: "Tutorial",
                to: "/docs/getting-started",
              },
            ],
          },
          {
            title: "More",
            items: [
              {
                label: "GitHub",
                href: "...",
              },
            ],
          },
        ],
        copyright: `Copyright © ${new Date().getFullYear()} ...`,
      },
      prism: {
        theme: lightCodeTheme,
        darkTheme: darkCodeTheme,
        additionalLanguages: ["java", "scala", "gradle"],
      },
    }),
};

module.exports = config;
```
2. Generate api docs with `npm run docusaurus gen-api-docs all`
3. Start server `npm run start`
4. Go to any page that would have code snippet tabs on it.

## Screenshots

<img width="527" alt="Screenshot 2022-09-05 at 16 25 34" src="https://user-images.githubusercontent.com/30095183/188481283-64368222-287b-43a8-9e6a-02b236c1f2aa.png">

<img width="495" alt="Screenshot 2022-09-05 at 16 26 13" src="https://user-images.githubusercontent.com/30095183/188481355-bc99c1ab-9b7c-401f-a7c9-0e7b0858a285.png">

## Context

I've never used Docusaurus before and was using Redocusaurus earlier today, but it didn't have multi-language code-snippets, so I switch to this package. I'm not sure if I've just set it up incorrectly or if it's a bug. Really sorry if it's my fault!

## Your Environment

- Version used: 1.1.10
- Operating System and version (desktop or mobile): Desktop macOS

**Comment by sserrata** [comment]
Hi @calthejuggler, the plugin currently requires Docusaurus v2.0.1. The error you are seeing suggests you might be on an earlier version?

**Comment by calthejuggler** [comment]
Hey @sserrata, thanks for your response! Downgrading to Docusaurus v2.0.1 fixed it, but previously I was on v2.1.0.

**Comment by sserrata** [comment]
Ah ok, that would have been my next guess. We should be upgrading to v2.1.0 early this week barring any breaking changes.

**Comment by calthejuggler** [comment]
Great, thanks! Looking forward to it
