### ISSUE TITLE
Generated info filename is odd when the API Title is mixed case

### ISSUE THREAD

**Issue by r-colvin** [PaloAltoNetworks/docusaurus-openapi-docs#266]
## Describe the bug

An API definition where the title contains mixed case, causes the *.info.mdx to have an unexpected/odd filename

## Expected behavior

an API definition with the following header

```
openapi: 3.0.1
info:
  title: "A Buggy ApI Description"
```

should generate a *.info.mdx file called `a-buggy-api-description.info.mdx`

## Current behaviour

the *.info.mdx file instead is call `a-buggy-ap-i-description.info.mdx` 

## Steps to reproduce

1. Create an API with mixed case inside the title (currently I believe it is mixed case inside a single word)
2. build the mdx files
3. observe the info.mdx file naming

## Context

no major impact

## Your Environment

- docusaurus 2.1.0
-  OpenAPI plugin 1.1.12

**Comment by sserrata** [comment]
Hi @r-colvin, this is expected behavior. The `kebabCase` method attempts to split the string by words and using mixed case formats in the same string can throw it off. 

Changing the string to "A Buggy API Description" or even "ABuggyApiDescription" would yield the desired output.
