### ISSUE TITLE
Automatically inject API Update date from Git History into Front Matter

### ISSUE THREAD

**Issue by r-colvin** [PaloAltoNetworks/docusaurus-openapi-docs#270]
### Is your feature request related to a problem? 
- no

I store and version control my API specs using Git and consider the MDX output of the gen-api-docs call as build artifacts - as such i have set my .gitignore file to igore the generated MDX files.

the consequence of this is that it is not possible to infer the updated date for these MDX files. At build time we see

`[WARNING] Cannot infer the update date for some files, as they are not tracked by git.`

however, the build time is actually not when the API was last updated. It would be good to be able to somehow add the update string to the front matter of the generated MDX

### Describe the solution you'd like

an option has been discussed in discord - 

![image](https://user-images.githubusercontent.com/18327771/191249822-53d989fb-1bec-4ebd-bf6f-e326dc3644e7.png)

a change in the overall spec would show an update for each path which might not be true. I am not sure how to resolve this at this time!

**Comment by sserrata** [comment]
Hi @r-colvin, have you tried using [last_update](https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-content-docs#last_update)? If it works for you, one possible approach could be to add a placeholder like the following to a Docusaurus OpenAPI docs [template](https://docusaurus-openapi.tryingpan.dev/#config) and then find and replace the value during build time:

```yaml
last_update:
    date: 1970-01-01 // placeholder value (remove this comment before trying)
    author: Steve Ballmer
```

Command to replace date with desired date:

```shell
sed -i'.bak' -e 's/1970-01-01/2022-09-20/g' api.mustache
```

Here's the full template for your reference:

```
---
id: {{{id}}}
description: "{{{description}}}"
{{^api}}
sidebar_label: Introduction
{{/api}}
{{#api}}
sidebar_label: {{{title}}}
{{/api}}
{{^api}}
sidebar_position: 0
{{/api}}
hide_title: true
{{#api}}
hide_table_of_contents: true
{{/api}}
{{#json}}
api: {{{json}}}
{{/json}}
{{#api.method}}
sidebar_class_name: "{{{api.method}}} api-method"
{{/api.method}}
{{#infoPath}}
info_path: {{{infoPath}}}
{{/infoPath}}
custom_edit_url: "https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/issues/new?labels=documentation&template=documentation_problem.md&title=[Documentation] Requesting changes to '{{{title}}}' ({{{id}}})"
last_update:
    date: 1970-01-01
    author: Steve Ballmer
---

{{{markdown}}}
```

**Comment by r-colvin** [comment]
@sserrata  thanks, yes i am using last_update and as I have a few custom build steps I can include this there as well

if you see this as the preferred solution we can close this enhancement request; or we can keep the request if you feel it is something worth including in the main release
