### ISSUE TITLE
[Enhancement] Introduce BEM-style classnames to theme components

### ISSUE THREAD

**Issue by sserrata** [PaloAltoNetworks/docusaurus-openapi-docs#275]
### Is your feature request related to a problem?

There's limited CSS selectors available to override styles in `ApiItem` and `ApiDemoPanel`.

### Describe the solution you'd like

BEM-style classes should exist on all appropriate theme components to better support overriding styles.

### Describe alternatives you've considered

n/a

### Additional context

See #249 for additional context.

**Comment by JoarLeth** [comment]
Hey! 👋
I think this would be really valuable and I'd love to contribute to it. I submitted a draft PR (https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/pull/389) that I would love to get some initial feedback on.

**Comment by sserrata** [comment]
Now available in v2.0.0
