### ISSUE TITLE
OpenAPI Specification Extension Support

### ISSUE THREAD

**Issue by r-colvin** [PaloAltoNetworks/docusaurus-openapi-docs#279]
### Is your feature request related to a problem? 
- No

As discussed on Discord: https://discord.com/channels/398180168688074762/867060369087922187/1022259147636473886 

OpenAPI supports specification extensions (those that start with x-) - PA OpenAPI has some support currently, however it would be benefical to render those that the plugin doesn't know what to do with as documentation

### Describe the solution you'd like

an example would be how Swagger.io handles these

![image](https://user-images.githubusercontent.com/18327771/191745798-d07f0984-61be-4abf-9be5-604a655690f2.png)

**Comment by sserrata** [comment]
Hi @r-colvin, thanks for the recommendation. I think, minimally, we should document the extensions supported by the plugin. Outside of that, I would like to better understand why we should support discovering and rendering extensions like the one in your example. Do you have any concrete/practical examples that you can share? I understand the relationship between `x-dummy-data` and what is rendered in Swagger UI but I would like to see a real-world example.

**Comment by Mikescops** [comment]
Hello,

What's the status on this issue?

@sserrata I have good use cases for extension that is not covered by default OpenAPI keys.
For instance, we need to give information about the rate limit applied by the server on specific endpoints, this information is only necessary for client developers to know what kind of caching they should apply.

<img width="385" alt="image" src="https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/assets/4266283/aa65f4ba-05ca-44f0-a5dc-49d4b282407b">

**Comment by Mikescops** [comment]
@r-colvin @sserrata when I wanted to do a PR I figured out while reading the code that there is actually an option to rend the `x-` fields in a simple way (that is good enough in my use case).

You can use `showExtensions: true` in your config.

<img width="782" alt="image" src="https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/assets/4266283/d0c5f1e7-6368-4d1b-9ab0-1c0d33200c20">

Maybe there is room to improve a little bit the UI but that's fine for now.

**Comment by r-colvin** [comment]
@Mikescops  thanks mate! really appreciate the ping; I will need to check into this! but really, thanks for thinking of me! :)
