### ISSUE TITLE
[Enhancement] Support for requestBody examples

### ISSUE THREAD

**Issue by r-colvin** [PaloAltoNetworks/docusaurus-openapi-docs#280]
### Is your feature request related to a problem?
- No

As discussed on Discord (https://discord.com/channels/398180168688074762/867060369087922187/1022457676577378386)

if you provide multiple examples in the api spec, the plugin will only render the first to the "body" and "code sample" boxes

### Describe the solution you'd like

as in other parts of the page, provide tabs for the various examples

**Comment by sserrata** [comment]
To paraphrase, this is a request for `requestBody` examples, similar to how `responseBody` examples work today. The idea is that the user would be presented with tabs from which they could choose from available `requestBody` examples to display. Additionally, when an example is selected the generated code sample should be updated accordingly.

**Comment by sserrata** [comment]
Hi @r-colvin, finally merged a change that introduces requestBody example(s) support. I appreciate if you can help test.
