### ISSUE TITLE
[Bug] Duplicate routes when tag matches endpoint

### ISSUE THREAD

**Issue by jordan-violet-sp** [PaloAltoNetworks/docusaurus-openapi-docs#282]
## Describe the bug

We have a tag (search) that matches an endpoint in our OpenAPI spec (also search).

## Expected behavior

The slug for the sidebar category should be different than the slug for the endpoint.

## Current behavior

We end up with the category doc being unreachable because the slug for the endpoint was created last. See attached image.

## Possible solution

A possible solution might be to append the CRUD operation type to the url's of the endpoints so they're always unique?

## Steps to reproduce

No need. You can see our tag and matching endpoint here, lines 219 and 373 respectively.

## Screenshots

![image](https://user-images.githubusercontent.com/69053702/192420880-763bd7bf-35b0-445c-9b6c-9cd5b261b462.png)

## Context

Unable  to have a successful user experience if the collection description is unreachable.

## Your Environment

N/A

**Comment by sserrata** [comment]
Hi @jordan-violet-sp, thanks for reporting this issue. It appears to be an edge case where the IDs for "tag docs" and "API docs" can end up being the same, resulting in conflicting routes.

I think the most expedient way to address this in the plugin would be to add some unique suffix/prefix to the "tag doc" ID. That said, there are other ways to avoid/overcome it:

* Change the tag name or define an `x-displayName` to override the name.
* Change the `operationId`, e.g. from `search` to `createSearch`, or `searchByQuery` or something like that.
* Remove the `operationId` from the operation so it falls back to using the `summary` as the doc ID.

I'm a bit conflicted over how to move forward. All the example `operationId` values I've come across are typically some combo of "verb" + "resource", e.g. `createPet`, `filterByTag`, `deleteUser`, etc. Of course, the spec 100% allows for `operationId` values like `search`, so it really comes down to adopting a convention that works best for you and your use case.

We could choose to add a unique suffix/prefix to each "tag doc" or "api doc" but it wouldn't 100% help avoid a conflict, just make it less likely to occur. For that reason, I'm not entirely sure what the best path forward would be.

**Comment by sserrata** [comment]
Will re-open if needed.
