### ISSUE TITLE
Common param is rendered incorrectly

### ISSUE THREAD

**Issue by changsheng1239** [PaloAltoNetworks/docusaurus-openapi-docs#291]
## Describe the bug

If a common param is used, the generated docs did not render the param at all. 

## Expected behavior

![image](https://user-images.githubusercontent.com/29444534/195077419-44dbb7d6-bb5e-4028-b00f-584af49fba7b.png)

## Current behavior

![image](https://user-images.githubusercontent.com/29444534/195077215-c3fa2339-6f89-4ffb-ac20-3495cc33bc34.png)

## Steps to reproduce

```
 "/companies/{name}":
    parameters:
      - schema:
          type: string
          example: Company%20A%20SDN%20BHD
        name: name
        in: path
        required: true
        description: url encoded company name
    get:
      summary: Query company by name
      tags:
        - companies
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Company"
      operationId: get-companies-name
      description: Get a company by its name
    put:
      summary: Update company by name
      operationId: put-companies-name
      ...
    delete:
      ...
```

## Your Environment

Docusaurus: 2.1.0
docusaurus-plugin-openapi-docs: 1.2.2
OS: Windows 11

**Comment by sserrata** [comment]
Hi @changsheng1239, I tested using your sample operation and it appears to be working as expected:

https://user-images.githubusercontent.com/9343811/195088455-fed14470-c06a-4bcf-9500-4fa69a7b929a.mov

Maybe I am misunderstanding something?

**Comment by sserrata** [comment]
Hi @changsheng1239, thanks for reporting this issue. I was able to find the source documentation describing the expected behavior: https://swagger.io/docs/specification/describing-parameters/#:~:text=header%20instead.-,Common%20Parameters,-Common%20Parameters%20for

We'll consider this a feature request. Thanks!

**Comment by changsheng1239** [comment]
@sserrata just tested the canary release `0.0.0-475` and it is indeed working now! Thanks 👍
