### ISSUE TITLE
Use `example` value instead of `default`

### ISSUE THREAD

**Issue by OzzyCzech** [PaloAltoNetworks/docusaurus-openapi-docs#296]
### Is your feature request related to a problem?

There should be switch or something in config that allow us use `example` value instead of `default` or primitives in **Example (from schema)**.

![image](https://user-images.githubusercontent.com/105520/195881969-6d9088af-2964-4ec0-a6f2-dcfa34858262.png)

I've been looking at the code, there is TODO 😄 

https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/blob/becd0aeaca03d8a8aa1158ef883bfeea5540d7e4/packages/docusaurus-plugin-openapi-docs/src/openapi/createResponseExample.ts#L83-L86

### Describe the solution you'd like

Would be nice use `example` when it's set or let developer chose what's they want.

### Additional context

Let's check Swagger, they also use `example` values in example json Responses instead of string

**Comment by sserrata** [comment]
Hi @OzzyCzech, thanks for reporting this issue. Can you share your OpenAPI spec or a snippet corresponding to the screenshot you provided?

**Comment by OzzyCzech** [comment]
Sure @sserrata here is my project https://github.com/testomato/help.testomato.com/ and mine OpenAPI [yaml file](https://github.com/testomato/help.testomato.com/blob/master/src/testomato.yaml)

**Comment by sserrata** [comment]
Thanks! I just tested locally (after uncommenting the lines you cited) and got the following:

<img width="619" alt="Screen Shot 2022-10-17 at 10 41 58 AM" src="https://user-images.githubusercontent.com/9343811/196207230-c1818274-99c5-43c9-adfb-946fc7ec552b.png">

Is that what you would expect?

**Comment by OzzyCzech** [comment]
Yes, that's what should be there

**Comment by sserrata** [comment]
Thanks. I believe it's safe to merge the change but I'd like to do a bit more testing before releasing in production, just to make sure. That said, I'll ping you when a canary release is available to test with.

**Comment by OzzyCzech** [comment]
Sure, thank you very much.

**Comment by sserrata** [comment]
Here's the canary release if you'd like to preview/test the change: `0.0.0-480`
