### ISSUE TITLE
union of types combined with `anyOf` in content schema crashes the site 

### ISSUE THREAD

**Issue by maciekpitucha** [PaloAltoNetworks/docusaurus-openapi-docs#297]
## Describe the bug

The following schema crashes the website:

```yaml
---
openapi: 3.1.0
info:
  title: test API
  version: "1.0"
paths:
  "/test_anyof":
    post:
      summary: summary
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                ipaddr:
                  anyOf:
                    - type:
                        - string
                        - "null"
                      description: IPv4 address
                    - type:
                        - string
                        - "null"
                      description: IPv6 address

```

## Expected behavior

The website does not crash and correctly displays union of types `["string", "null"]`

## Current behavior

![image](https://user-images.githubusercontent.com/114495507/195923930-c2051611-545c-4d85-a246-142257d23437.png)

[browser console log](https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/files/9789534/localhost-1665775609813.log)

## Possible solution

 It appears to be related to two things:
- `anyOf` 
- union of types
    ```yaml
    type:
       - string
       - null
     ````

`anyOf` with primitive types works just fine and union of types without `anyOf` (still only ignores the `null` when displaying but that's minor).

## Steps to reproduce

1.  Use the schema from this issue
2. `yarn docusaurus gen-api-docs all`
3. `yarn start`
4. go to the page that shows API schema

## Context

My SaaS company has a very complex schema. I'm evaluating various solutions to display it in our official docs and Docusaurus and your plugin would be our top choice but we're struggling to get it up and running.

## Your Environment

- Version used: "docusaurus-plugin-openapi-docs": "^1.2.2"
- Environment name and version (e.g. Chrome 59, node.js 5.4, python 3.7.3): Chrome Version 106.0.5249.103 (Official Build) (arm64)
- Operating System and version (desktop or mobile): macOS Monterey 12.6
- Link to your project:

**Comment by sserrata** [comment]
Hi @maciekpitucha, I believe type only accepts a single value when following OpenAPI specification.

Reference: https://swagger.io/docs/specification/data-models/data-types/
