### ISSUE TITLE
Referenced examples not shown in schema

### ISSUE THREAD

**Issue by sradu** [PaloAltoNetworks/docusaurus-openapi-docs#311]
## Describe the bug

Let's say I have an interface like:

```
"RelationValueInterface": {
  "type": "object",
  "properties": {
    "href": {
      "type": "string",
      "description": "Link to another request.",
      "example": "https://example_link"
    }
  },
  "required": [
    "href"
  ]
},
```

Which is integrated like:

```
"ModelInterface": {
  "type": "object",
  "properties": {
    "link_stuff": {
      "$ref": "#/components/schemas/RelationValueInterface"
    },
  }
}
```

Inside the response schema (from example) I see "string" instead of the actual example:

<img width="134" alt="Screen Shot 2022-10-25 at 6 35 30 PM" src="https://user-images.githubusercontent.com/82214/197914051-638026df-784d-4371-afb7-18d2e0a9980f.png">

Swagger shows this OK.

## Expected behavior

I would expect to see the example from the reference.

## Current behavior

I see "string"

Thank you

**Comment by sserrata** [comment]
Hi @sradu, can you share what version of the plugin/theme you are using?

**Comment by sradu** [comment]
@sserrata apologies should have not deleted the last part. Using the latest version, 1.3.2.

**Comment by sserrata** [comment]
Thanks, we'll try to reproduce. This should have been addressed in `v1.3.1` but it's possible it's an edge case we are not covering.

**Comment by sradu** [comment]
Maybe because it's a couple of layers down via $ref? 

`MainObjInterface` has properties `ChildObjInterface` has properties `SubChildObjInterface` which has the example?

**Comment by sserrata** [comment]
It's a possibility..although all JSON and OpenAPI pointers should be pre-resolved prior to this stage...Do the examples appear under the Schema property (left hand side)?

**Comment by sradu** [comment]
They don't appear there. Swagger shows them.

**Comment by sserrata** [comment]
I'm wondering if there's an opportunity to extract the `example` here: https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/blob/main/packages/docusaurus-plugin-openapi-docs/src/openapi/createRequestExample.ts#L180

Basically something like...

```javascript
let { type, format, example } = schema;

if (example) {
  return example
}
```

**Comment by sradu** [comment]
Want me to email you the full spec I'm working on?

**Comment by sserrata** [comment]
Sure, that would help. Thanks.

**Comment by sradu** [comment]
A million apologies. This was a bad bug report.

I updated the deps in my package.json but ran `rush update` out of habit instead of `npm i`. We removed docusaurus from our rush build because it just wouldn't work.

The examples are showing up correctly with the last release.
