### ISSUE TITLE
Increase request execution timeout duration for "Try it" feature in ApiDemoPanel

### ISSUE THREAD

**Issue by devgeetech** [PaloAltoNetworks/docusaurus-openapi-docs#327]
## Describe the bug

For the "Try It" feature, if the request takes more than 5 seconds to complete execution, the ApiDemoPanel will show a "Connection Failed" error.

## Expected behavior

The ApiDemoPanel shows the response even if the request takes more than 5 seconds to complete

## Current behavior

The ApiDemoPanel shows a "Connection Failed" error. The request actually completes its execution and returns a response (verified from the network tab)

## Possible solution

The timeout is hardcoded in [makeRequest.ts](https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/blob/main/packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/Execute/makeRequest.ts) (line 15). If there is no specific reason for choosing that value, it can be increased to a higher timeout.

Another option is to add a new plugin config variable that let's the user choose a timeout value themselves.

## Steps to reproduce

Can be reproduced by sending an API requesting in the ApiDemoPanel that takes more than 5 seconds to return a response.

## Context

I am building the documentation for a text-to-speech API that sometimes takes a fair bit of time to generate a response. It would be awesome if the "Try it" feature worked for slower APIs too.

## Your Environment

- Version used: 1.2.1

**Comment by sserrata** [comment]
Hi @devgeetech, thanks for reporting this issue. I think a new plugin config option that allows users to configure the `timeout` makes sense. We'll add it to our backlog of feature requests.

**Comment by sserrata** [comment]
@devgeetech, we recently improved support for swizzling OpenAPI docs theme components, including the `makeRequest.ts` module that handles generating the request. That said, it should be possible to swizzle in order to override the timeout.

**Comment by sserrata** [comment]
Closing since this option is now supported with swizzling. Will revisit possibility of adding a `timeout` plugin option in the future.
