### ISSUE TITLE
Is there a way to customise the code behind "Send API Request"?

### ISSUE THREAD

**Issue by MJWang2022** [PaloAltoNetworks/docusaurus-openapi-docs#329]
### Is your feature request related to a problem?

No

### Describe the solution you'd like

I hope I can use my own way to encrypt my request (i.e. generate a signature and send it out)

**Comment by sserrata** [comment]
Hi @MJWang2022, it might be possible to swizzle the `ApiDemoPanel/Execute` to override the request but this is untested.

**Comment by MJWang2022** [comment]
@sserrata Thank you; I managed to figure something out. One more question, how to specify a default value for parameters in "api":
"parameters":[{"name":"coin","in":"query","description":"Specify coin","required":false,"style":"form","schema":{"items":{"type":"string","default":"available"}}}]

Above configuration will require me to input. How to pre-configure a default value?

**Comment by sserrata** [comment]
Hi @MJWang2022, the plugin respects default or example property values in the OpenAPI specification. You should be able to define those in your request schemas/properties.

**Comment by MJWang2022** [comment]
"We can look into supporting this." - I will appreciate if you could support this. It's gonna improve user experience significantly

**Comment by MJWang2022** [comment]
BTW, is there a document to show all functions available for the json structure I can use after "api"?:[{"name":"coin","in":"query","description":"Specify coin","required":false,"style":"form","schema":{"items":{"type":"string","default":"available"}}}]

**Comment by sserrata** [comment]
Hi @MJWang2022, the `api` JSON structure is derived from the OpenAPI spec itself. It's basically the props for a given operation/endpoint.

**Comment by sserrata** [comment]
Recent merge includes support for swizzling the `makeRequest.ts` module and `Execute` component, which should allow for customizing the request. Will be included in next release but can be previewed in canary release.
