### ISSUE TITLE
<option> elements do not have background color defined

### ISSUE THREAD

**Issue by TheCatLady** [PaloAltoNetworks/docusaurus-openapi-docs#342]
## Describe the bug

Dropdown menus are difficult to see/read in dark mode.

## Expected behavior

Dropdown menus should be styled appropriately in dark mode.

## Current behavior

`<option>` elements do not have background color defined, and as a result the light text color in dark mode becomes difficult to read.

## Possible solution

Define background color for `<option>` elements.

## Steps to reproduce

1. Visit https://docusaurus-openapi.tryingpan.dev/petstore/get-inventory
2. Click `Edit` next to `Base URL`
3. Open dropdown menu

## Screenshots

<img width="340" alt="image" src="https://user-images.githubusercontent.com/52870424/201487617-caf1fd60-546f-4d3c-9018-69374e82fcb3.png">

## Context

N/A

## Your Environment

N/A

**Comment by TheCatLady** [comment]
Ah, the issue appears to be that `--openapi-input-background` is not defined. 😄

**Comment by sserrata** [comment]
Hi @TheCatLady, thanks for reporting the issue. We did recently refactor how styles are exported by the theme so it's possible we broke something.

 Are you seeing the issue across different browsers? So far I've been unable to reproduce.

**Comment by TheCatLady** [comment]
> Are you seeing the issue across different browsers? So far I've been unable to reproduce.

I've only tested on Windows Chrome. DevTools also shows that the CSS variable `--openapi-input-background` is not defined:
<img width="293" alt="image" src="https://user-images.githubusercontent.com/52870424/201773734-e0c43ce2-0c45-42d8-93a2-87fb971f8641.png">

I was also able to mitigate this issue on our Docusaurus install by defining the value of `--openapi-input-background`: https://github.com/someengineering/resoto.com/pull/443/files

**Comment by sserrata** [comment]
Hi @TheCatLady, thanks for the additional detail/context. I added the `--openapi-input-background` variable back in #344 and matched it to the card background by default. Of course, this can always be overridden as you have demonstrated.

Let me know if this works/makes sense.
