### ISSUE TITLE
downloadUrl should work as a Docusaurus static link

### ISSUE THREAD

**Issue by jordan-violet-sp** [PaloAltoNetworks/docusaurus-openapi-docs#348]
### Is your feature request related to a problem?

You have to provide an already existing url to a spec to download.

### Describe the solution you'd like

We'd like to be able to provide a static link to a local file to download the API specification. In this case, we'd like to provide the url 'files/spec.json' and Docusaurus would render the link at build.

**Comment by sserrata** [comment]
Hi Jordan, I think you're asking if the OpenAPI spec file can be imported and bundled using webpack? It's definitely possible but we'd want to make sure it's not being altered during the compilation/build process.
