### ISSUE TITLE
allOf not displayed correctly when part of an array type

### ISSUE THREAD

**Issue by philip-ellis-sp** [PaloAltoNetworks/docusaurus-openapi-docs#349]
## Describe the bug

If I have a spec defined with an array with items that are allOf under it, the generated documentation does not show the response correctly

## Expected behavior

The response should show all of the objects defined in the schema.

## Current behavior

Currently, the only thing that is displayed is the text "allOf" Example below:

![image](https://user-images.githubusercontent.com/94471173/202759632-9ba58e10-1be7-46a2-b484-78bc00721d7f.png)

## Possible solution

Unsure at this time.

## Steps to reproduce

Live example can be found here: https://developer.sailpoint.com/idn/api/v3/list-identity-profiles/

to reproduce this bug, you can create a schema with a response that has an array type with allOf in the items. An example response yaml:

```yaml
  responses:
    '200':
      description: List of identityProfiles.
      content:
        application/json:
          schema:
            type: array
            items:
              allOf:
              - type: object
                properties:
                  id:
                    description: System-generated unique ID of the Object
                    type: string
                    example: id12345
                    readOnly: true
              - type: object
                properties:
                  description:
                    type: string
                    description: The description of the Identity Profile.
                    example: My custom flat file profile
                    nullable: true
```
Then generate the documentation and not that the all of is not presented properly. 

## Context

Our specification has a few instances of this scenario and they are not rendered properly on the page. I tried limiting the schema to just two objects and the error still persisted. I also switched it from allOf to oneOf and the oneOf was presented just fine, so it appears to be limited to just the allOf type.

## Your Environment

- Version used: 
"docusaurus-plugin-openapi-docs": "^1.4.5",
"@docusaurus/core": "^2.2.0",

**Comment by sserrata** [comment]
Available for testing in `0.0.0-522`. Thanks!
