### ISSUE TITLE
Limit what a customer sees in the listed API

### ISSUE THREAD

**Issue by jeffpascal** [PaloAltoNetworks/docusaurus-openapi-docs#362]
### Is your feature request related to a problem?

I would like to present an API portal to multiple customers. 

The company I am at has different customers that use different parts of the API. 

For example:

API 1

- route 1 (used by client 1)
- route 2 (used by client 2)
- route 3 (internal)

The internal one should be invisible, and the other routes should only show up to the customers that have access to it.

### Describe the solution you'd like

I was thinking of adding customer TAGS to the API. 

Example:

API 1

- route 1 (tag client 1)
- route 2 (tag client 2)
- route 3 (tag internal)

Then through SSO, have the frontend only show tags based on e-mail address.

As far as I know, there is no way of doing this.

### Describe alternatives you've considered

I've also considered deleting from API specs the routes that do not have the client specific tags, and building a different api portal for each client. This still needs to be tested.

### Additional context

I believe having a way to show only some api's to different companies makes sense, even more on legacy apps, where API's are big, and not all of them are used by all customers.

**Comment by sserrata** [comment]
Hi @jeffpascal, if I'm understanding correctly you're wanting to gate access to specific endpoints/routes? This is outside the scope of the OpenAPI docs plugin but, FWIW, you might want to explore a server-side auth/authz solution capable of proxying requests to your Docusaurus site, e.g. Netlify auth (JWT), AWS Cognito or Google Identity Toolkit + API Gateway and cloud storage.
