### ISSUE TITLE
Swagger 2.0 spec does not always get correct requestBody

### ISSUE THREAD

**Issue by gustavste** [PaloAltoNetworks/docusaurus-openapi-docs#372]
## Describe the bug

Using a swagger 2.0 spec, some requests does not get the correct requestBody. In the front matter api it looks something like: `requestBody: {'$ref': ''#/components/requestBodies/OperationIdReq'} `

## Expected behavior

The body json should be present
## Current behavior

For some requests the $ref doesn't seem to get resolved.
## Possible solution

I tried adding `resolveInternal: true` [here](https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/blob/1a67184bd2aff7586314cd2e0d60c3808ccd5975/packages/docusaurus-plugin-openapi-docs/src/openapi/utils/loadAndResolveSpec.ts#L69)
and it seems to work. 
Either this could be updated, or provide a way to pass options to it.
## Steps to reproduce

I haven't figured out exactly what types of $refs that doesn't work, as some requestBodies of the same swagger 2 spec gets generated as expected. The swagger spec is autogenerated and I noticed some generated request bodies contain the exact same properties, and perhaps are considered the same by the tool.
When I tried using `swagger2openapi`-cli locally it worked just fine.

## Context

For some requests the request body is missing, similar to https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/issues/369

## Your Environment

- docusaurus: 2.2.0
- Version used: 1.5.0
- Operating System and version (desktop or mobile): windows 10

**Comment by sserrata** [comment]
Hi @gustavste, thanks for reporting this issue. Can you provide a reference for the `resolveInternal: true` option? I am not able to find it in the documentation: https://apitools.dev/json-schema-ref-parser/docs/options.html

**Comment by gustavste** [comment]
Hi @sserrata 
I found it here: https://github.com/Mermade/oas-kit/blob/main/docs/options.md

looking through the code it is `swagger2openapi` that is used, right?
https://github.com/Mermade/oas-kit/tree/main/packages/swagger2openapi

**Comment by sserrata** [comment]
Ah I see, yes you're correct. In that case I think it makes sense to add the option, if it addresses your issue. I think my initial expectation was that it would first upconvert to 3.0 and then resolve $refs.

**Comment by sserrata** [comment]
By the way, feel free to open a PR for this issue - would definitely prefer you get credit.

**Comment by gustavste** [comment]
Smallest possible PR 😅

**Comment by sserrata** [comment]
Hi @gustavste, this change is available to test in `0.0.0-535`.
