### ISSUE TITLE
Can't Swizzle DocApi components

### ISSUE THREAD

**Issue by selankon** [PaloAltoNetworks/docusaurus-openapi-docs#373]
## Describe the bug

I try to swizzle DocApi layout component, but when I do yarn start, changes are not shown. 

## Expected behavior

Swizzle a DocItem layout component,  modify it adding or deleting stuff, then run yarn start and show modification on any docs page

## Current behavior

I swizzle DocItem layout but changes are not shown

## Possible solution

Inspecting the document I see that is using classes from openapi-docs on any DocPage. Maybe I have to swizzle it from the  openapi-docs swizzle menu, but DocItems are not available. It seems that is like openapi-docs is swizzling this component and using it on top for all doc pages. 

Maybe a solution is to let swizzle the DocItems for openapi-docs? 

## Steps to reproduce

1. `yarn swizzle`
2. Select `@docusaurus/theme-classic` > `DocItem/Layout (Unsafe)`  and `eject` it
3. Modify generated file on theme > DocItem > Layout > index.js
4. Add some `<div>Hello World</div>` somewhere.
5. Do `yarn start` and check any doc item expecting to see the inserted dic

## Context

I'm trying to add https://giscus.app/ reactions to my page to see if the documentation is useful. 

## Your Environment

- Version used: `1.5.0`
- Environment name and version (e.g. Chrome 59, node.js 5.4, python 3.7.3): Firefox 
- Operating System and version (desktop or mobile): desktop linux
- Link to your project: developer.vocdoni.io/

**Comment by sserrata** [comment]
Hi @selankon, if you set `docItemComponent` to `ApiItem` you should swizzle `ApiItem` and not `DocItem` in order to customize the layout/component.

**Comment by selankon** [comment]
Ok that's right and this work for my use case, Thanks
