### ISSUE TITLE
Question: Usable for just regular documentation?

### ISSUE THREAD

**Issue by Zenahr** [PaloAltoNetworks/docusaurus-openapi-docs#380]
I found out that your plugin - besides handling a lot of stuff related to API documentation - also allows for multi-instance versioning with a context-sensitive version dropdown.

Would I be able to work with the plugin even though I won't have any openapi specs at all, but rather regular docs files in my docusaurus project?

**Comment by sserrata** [comment]
Hi @Zenahr, the versioning supported by this plugin is specific to handling versioned API docs. That said, have you explored Docusaurus [versioning](https://docusaurus.io/docs/next/versioning)?

Here's an example of what their implementation could yield: https://resoto.com/docs/reference

**Comment by Zenahr** [comment]
@sserrata Thanks for the reference. I was looking to see if your plugin would provide an out-of-the-box solution. Resoto have built a bit of custom code around things.
