### ISSUE TITLE
[HelpRequest] Is there a way to make the schema dropdown open by default

### ISSUE THREAD

**Issue by selankon** [PaloAltoNetworks/docusaurus-openapi-docs#383]
On a doc item page, at the bottom, there are the `SchemaItem` component which if is an object is collapsible.

I would like to set this expanded by default (instead as collapsed, as is right now). 

Do you have any idea of how get this? I tried modifying css classes, swizzling the component, but I don't found anything related.

**Comment by sserrata** [comment]
Hi @selankon, currently there is no good way to handle this since the `details` elements are part of the MDX that is statically generated when you run `gen-api-docs`.

That said, it may be possible to introduce a new plugin option to effectively set the expand level/depth prior to generation.

**Comment by selankon** [comment]
Ok thanks, I will wait for updates regarding this

**Comment by sushengloong** [comment]
> That said, it may be possible to introduce a new plugin option to effectively set the expand level/depth prior to generation.

Hi @sserrata, I need this feature and would like to help. Could you share some guidance, eg. which files and methods I should be looking at, to help me get started?

**Comment by davidmoltin** [comment]
@selankon @sushengloong if you are still interested in this, here is the CSS for removing the collapse. I came upon your thread looking for the same answer. 

`details > div,
details[open] > div {
  display: block !important; /* Force content visibility */
  height: auto !important;  /* Ensure full content height */
  overflow: visible !important; /* Show all content */
}`

If you want to remove the open / collapse arrow, add the following:

`.openapi-markdown__details > summary::before {
  display: none; /* Hide the arrow icon to avoid confusion */
}`

I also removed the background color and darkened the text:

`details {
  color: var(--docs-color-text-800) !important; /* Darken text */
  background: transparent !important; /* Remove background */
}`

**Comment by davidmoltin** [comment]
The other option, if you don't want to use CSS is to use javascript. I did this first but it felt a bit heavy handed. 

```javascript
document.addEventListener("DOMContentLoaded", () => {
  console.log("Details script loaded");

  // Single observer for the entire document
  const observer = new MutationObserver((mutations) => {
    const details = document.querySelectorAll("details");
    details.forEach(detail => {
      if (!detail.hasAttribute("open")) {
        detail.setAttribute("open", "");
      }
    });
  });

  // Observe changes to the document
  observer.observe(document.body, {
    childList: true,
    subtree: true,
    attributes: false
  });

  // Initial setup
  const details = document.querySelectorAll("details");
  details.forEach(detail => {
    detail.setAttribute("open", "");
  });
});
``` 

I saved this as always-open-details.js and loaded it from a script tag in my docusaurus.config.ts file.
