### ISSUE TITLE
False-y values are ignored in min/max/example

### ISSUE THREAD

**Issue by paulo-raca** [PaloAltoNetworks/docusaurus-openapi-docs#403]
## Describe the bug

One of my parameters has a range of [0,100], and I noticed that only the maximum is being shown in the docs.

After some testing, turns out that "false" has the same issue.

A quick'n'dirty fix to the docs is using strings instead, however it doesn't sound right to add a string as the maximum of a numeric argument

## Expected behavior

Zeros and falses should be displayed in min/max/examples

## Current behavior

Zeros and falses are ignored, just like the min/max/examples hadn't been provided

## Possible solution

I haven't seen the code for this, but looks like it might be implemented as `if (arg.example) {...}` instead of `if arg.hasOwnProperty("example")) {...}`

## Steps to reproduce

[Here is an example with several args, all of them with min/max/example.](https://gist.github.com/paulo-raca/c8524702c07d42fb541550608834eee3#file-openapi-json)

And here is how it looks like:

![Screenshot_20230202_152101](https://user-images.githubusercontent.com/1072660/216413035-d260fb22-6d7b-44a2-990d-a91ebe9c08f3.png)

**Comment by paulo-raca** [comment]
Looks good, thank you!

**Comment by sserrata** [comment]
Sharing screenshot for reference: 

<img width="701" alt="Screenshot 2023-02-16 at 12 59 11 PM" src="https://user-images.githubusercontent.com/9343811/219449137-e77ba9d4-edd2-4af3-827e-4c61ba274fb7.png">
