### ISSUE TITLE
how to convert postman collection into openapi

### ISSUE THREAD

**Issue by nitinmcsam** [PaloAltoNetworks/docusaurus-openapi-docs#407]

**Comment by jasikpark** [comment]
https://github.com/postmanlabs/postman-app-support/issues/1744#issuecomment-691920960

I would take this up w/ Postman? All that needs to happen is to generate an OpenAPI spec file/files from a Postman Collection, I'm unsure whether consuming Postman Collections directly would be in scope for this tool? I don't work on it though so 🤷

**Comment by sserrata** [comment]
For now the best route is to take this issue to Postman. You can also check out this library to see if it works: https://www.npmjs.com/package/postman-to-openapi

**Comment by nitinmcsam** [comment]
Ok thanks
