### ISSUE TITLE
OpenAPI 3.1 support?

### ISSUE THREAD

**Issue by IanVS** [PaloAltoNetworks/docusaurus-openapi-docs#410]
### Is your feature request related to a problem?

I was trying to use open api 3.1.0 syntax, but it seems to be causing problems, so maybe it's not supported?

### Describe the solution you'd like

Support 3.1.0

### Additional context

Is it already supported and I'm just using it wrong?  I do see `Compatible: Works with Swagger 2.0 and OpenAPI 3.x.` in the website, but when I tried to use `type: [string, 'null']`, the resulting span was just `stringnull` smashed together like that, whereas `nullable: true` added a nice `nullable` tag.

**Comment by sserrata** [comment]
Hi @IanVS, OpenAPI 3.1 definitely isn't supported, yet. FWIW, there are tools that will down convert to from 3.1 to 3.0 but there could be loss of features in the process. That said, our plugin does attempt to resolve _all_ JSON schema $ref pointers, regardless of whether or not they follow the OpenAPI spec.

**Comment by IanVS** [comment]
Thanks for confirming.  What would you think about making that clearer in the README?

**Comment by stefan-schweiger** [comment]
`3.1` would be really appreciated because you can now have a separate top level element for describing WebHooks

**Comment by sserrata** [comment]
> What would you think about making that clearer in the README? Maybe just change 3.x to 3.0?

I agree, that could definitely help make it clearer. 

Hi @stefan-schweiger, support for 3.1 is on the roadmap. We're hoping to have it ready for our v2.0.0 release in the next 2-3 months.

**Comment by jasikpark** [comment]
looks like this'll be a post-2.0 update? I can imagine it's some work to support multiple OpenAPI versions.

**Comment by sserrata** [comment]
Hi @jasikpark, it really depends. We use external libraries for parsing so it would really come down to:
* How well those libraries support OpenAPI 3.1
* Which unique OpenAPI 3.1 features we decide to support and how compatible those features are with existing UI

**Comment by jasikpark** [comment]
ok! thx for breaking that down - maybe this issue can contain the status of those deps

**Comment by IanVS** [comment]
Hi @sserrata, have you given any more thought to openapi 3.1 support?  In specific, I'm wishing we had the ability to describe the shape of dynamic keys on objects: https://github.com/OAI/OpenAPI-Specification/issues/1505.

**Comment by sserrata** [comment]
Hi @IanVS, I checked and there is a more recent release of `@redocly/openapi-core` that we can upgrade to. I tested a few OpenAPI 3.1 specs and it appears to offer some support, although I can't guarantee 100% support/coverage of all 3.1 features.

**Comment by sserrata** [comment]
Hi @IanVS, I was wondering if you've had a chance to test the new `@redocly/openapi-core` parser?

**Comment by IanVS** [comment]
Not yet, though I hope to before too long.  I'm a bit behind on upgrades and it's going to take a lot of reworking of our custom CSS to update to the latest plugin versions.  Was kind of holding off until there was word that docusaurus 3 is fully supported, which would give us even more reason to upgrade.

**Comment by IanVS** [comment]
I'm still on `2.0.0-beta.2` 🙈

**Comment by sserrata** [comment]
Closing as limited support for OpenAPI 3.1 is already available

**Comment by IanVS** [comment]
Hi @sserrata I finally updated to 3.0 of the plugin, and tried using openapi 3.1, but the issue remains that I described at the top of this issue, that using `[string, 'null']` results in `stringnull` instead of a `nullable` tag.  Would you like a separate issue for that?

**Comment by jasikpark** [comment]
Added an issue for that specific bug: https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/issues/950
