### ISSUE TITLE
Bearer auth security type adds empty Authorization component

### ISSUE THREAD

**Issue by IanVS** [PaloAltoNetworks/docusaurus-openapi-docs#411]
## Describe the bug

When using bearer auth, there's an un-expandable `Authorization` box shown above the demo request box.

## Expected behavior

Either it should show something useful, or just go away, I guess.  Would be nice to show the description that I've added for the bearer auth, I suppose.  Even better if I can customize this description per path+method, but I don't think that's part of the openapi spec.

## Current behavior

An empty, unclickable box is shown.

## Steps to reproduce

```
git clone https://github.com/IanVS/repro-docusaurus-openapi-issue.git
git checkout bearer-auth
npm i
npx docusaurus gen-api-docs all
npm start
```

Navigate to `/docs/petstore/add-pet`

Notice that there is an "Authorization" box, that looks clickable, but does not expand to show anything.

Honestly I'd love to be able to show the api token's "scopes" that are required (we use scoped keys), but I know that scopes are only supported by oidc and oauth.  :(

## Screenshots

<img width="630" alt="image" src="https://user-images.githubusercontent.com/4616705/217669447-75b5b369-57c3-423d-be1c-eac20246c810.png">

## Context

Not a huge deal, just strange to show a thing that does nothing.

## Your Environment

- Version used: 1.5.1
- Environment name and version (e.g. Chrome 59, node.js 5.4, python 3.7.3): Brave, node 18
- Operating System and version (desktop or mobile): desktop macos
- Link to your project: https://github.com/IanVS/repro-docusaurus-openapi-issue/tree/bearer-auth

**Comment by IanVS** [comment]
My best bet might be to swizzle it, but I'm not sure how I'd be able to hack it to use some custom data per path+method.

**Comment by sserrata** [comment]
Hi @IanVS, thanks for reporting this issue. It's in our backlog to address with the goal to provide full coverage of all auth/security-scheme types.

**Comment by sserrata** [comment]
Upon second inspection, it looks like the security scheme defined in your repro is missing a `type`. That said, I think may just return `undefined` if the `selected` auth/options doesn't have `type` defined.

Something like:

```javascript
  if (options[selected]?.type === undefined) {
    return null;
  }
```

**Comment by IanVS** [comment]
I followed the example from https://swagger.io/docs/specification/authentication/bearer-authentication/

```
  securitySchemes:
    BearerAuth:
      description: >
        An API key with permissions needed for the endpoint
      type: http
      scheme: bearer 
```

What is it that is missing?  (I'm still learning the ins and outs of openapi).

**Comment by sserrata** [comment]
You're correct, nothing is missing in your usage. I believe what is happening is that options is the union of `security` and `securitySchemes` which is resulting in `type` not being defined. Will need to debug a bit more to be sure.
