### ISSUE TITLE
Dark mode logo does not work in prod on page load

### ISSUE THREAD

**Issue by IanVS** [PaloAltoNetworks/docusaurus-openapi-docs#421]
## Describe the bug

When I use an `x-dark-logo`, it works fine in development, but once it is built and served, it only works when dark mode is toggled on.  If the page is loaded in dark mode, the light logo is shown instead.  It works when navigating between pages as well.  It's just an issue on the initial page load.

## Steps to reproduce

Visit https://deploy-preview-94--dn-docs.netlify.app/API/defined-networking-api/.  Change to dark mode, you'll see the correct logo.  Refresh the page, and it will be the wrong one.

## Screenshots

<img width="678" alt="image" src="https://user-images.githubusercontent.com/4616705/218131555-5e997646-9683-410b-9cf5-aed398ff8304.png">

## Context

It's a bit ugly, is all.

## Your Environment

- Version used: 1.5.2
- Environment name and version (e.g. Chrome 59, node.js 5.4, python 3.7.3): Brave, Node 18
- Operating System and version (desktop or mobile): MacOS
- Link to your project: Closed source.

**Comment by sserrata** [comment]
Thanks for repoing @IanVS, looks like we need to retrieve and apply the initial/default theme state.

**Comment by sserrata** [comment]
@IanVS can you help test/review https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/pull/426 to see if it resolves the issue you reported? Thanks!

Deploy preview: https://docusaurus-openapi-36b86--pr426-e9kz1oxj.web.app/petstore/swagger-petstore-yaml/
