### ISSUE TITLE
Default values of `0` and `[]` are not shown correctly

### ISSUE THREAD

**Issue by IanVS** [PaloAltoNetworks/docusaurus-openapi-docs#432]
## Describe the bug

- Setting `default: 0` does not show up at all (maybe truthiness is being checked, instead of `undefined`?)
- Setting `default: []` appears as two backticks.

## Steps to reproduce

Pull down https://github.com/IanVS/repro-docusaurus-openapi-issue/tree/default-values, start it up, visit http://localhost:3000/docs/petstore/new-pet, and look at the dog pet type.  It doesn't have the default for pack size, and the default for packMembers looks wrong.

## Screenshots

<img width="374" alt="image" src="https://user-images.githubusercontent.com/4616705/218828906-1404403d-9a1e-4454-b4a1-8c794fdcf8d8.png">

## Context

I can work around this by wrapping the examples in quotes.

## Your Environment

- Version used: 1.5.1
- Environment name and version (e.g. Chrome 59, node.js 5.4, python 3.7.3): Brave, Node 18
- Operating System and version (desktop or mobile): desktop macOS
- Link to your project:

**Comment by sserrata** [comment]
Nice catch @IanVS, we may need to conditionally cast these values to string so they can be properly rendered.

**Comment by jasikpark** [comment]
0?.toString() should return "0" though, right?

**Comment by sserrata** [comment]
> 0?.toString() should return "0" though, right?

Yes, as should `String(0)` and `0 + ""`. The idea is that we should always end up with a string representation of the default value.

**Comment by sserrata** [comment]
Fix available in canary release `0.0.0-559`
