### ISSUE TITLE
Invalid sidebar.js created if outputDir has trailing slash

### ISSUE THREAD

**Issue by IanVS** [PaloAltoNetworks/docusaurus-openapi-docs#433]
## Describe the bug

I'm trying out the sidebar.js slice that's generated, but was hitting a problem when I try to use it.  

```
[ERROR] Error: Invalid sidebar file at "sidebars.js".
These sidebar document ids do not exist:
- api//create-host-and-get-enrollment-code
- api//defined-networking-api
- api//delete-host

Available document ids are:
- api/create-host-and-get-enrollment-code
- api/defined-networking-api
- api/delete-host
```

Eventually I figured out this was because I had set `outputDir` in the `docusaurus-plugin-openapi-docs` options to `docs/api/`.

## Expected behavior

I think the trailing slash could be stripped when generating sidebar entries, or an error could be thrown if a slash is detected.

## Current behavior

Duplicate slashes are used in sidebar.js, which causes problems.

## Steps to reproduce

Add a trailing slash to `outputDir` in a demo.

**Comment by sserrata** [comment]
Available to test in canary release `0.0.0-558`
