### ISSUE TITLE
Example integer from schema does not respect minimum value

### ISSUE THREAD

**Issue by IanVS** [PaloAltoNetworks/docusaurus-openapi-docs#437]
## Describe the bug

I have a schema that requires a value be a minimum of 1, but the default example that is generated from the schema shows it as `0`, which is invalid.

## Expected behavior

I would expect integers in the example to be valid.

## Possible solution

If there's a `minimum`, maybe that can be used instead of always `0`?

## Steps to reproduce

Clone https://github.com/IanVS/repro-docusaurus-openapi-issue/tree/minimum-example and start it up.

Visit http://localhost:3000/docs/petstore/get-order-by-id, notice that although the id has to be `>= 1`, the example provided is `0`

## Screenshots

<img width="415" alt="image" src="https://user-images.githubusercontent.com/4616705/219062939-2daa3376-8f54-4b6b-be1b-7750c6bd633d.png">

<img width="376" alt="image" src="https://user-images.githubusercontent.com/4616705/219062958-4bcb7dc7-f9d8-44c8-b197-94c0a277652a.png">

**Comment by sserrata** [comment]
Hi @IanVS, the generated example currently doesn't respect qualifiers which is a known limitation. That said, you should be able to directly set the generated value using either `example` or `default`.
