### ISSUE TITLE
[FR] Clean up intro support UI when only a url

### ISSUE THREAD

**Issue by IanVS** [PaloAltoNetworks/docusaurus-openapi-docs#447]
### Is your feature request related to a problem?

It's not so big of a problem, but the generated `Contact` section looks a bit awkward when there is only a URL provided:

<img width="515" alt="image" src="https://user-images.githubusercontent.com/4616705/220402287-ca1444a9-dd26-43ae-95a3-5a110110d333.png">

### Describe the solution you'd like

Maybe `API Support:` can be omitted when an email is not provided?  And `URL:` is a bit unnecessary there too, since it's pretty obvious that it is a URL.

**Comment by IanVS** [comment]
Doh, I just realized this is coming from the `name` we provided in the spec.  If I remove that, the `API Support` disappears.  I still think maybe `URL` could be removed though too, perhaps?  Feel free to close this out though.

**Comment by sserrata** [comment]
Thanks @IanVS, the labels are patterned after Redoc and other OpenAPI doc tools. I agree that "URL" feels unnecessary/implied.

**Comment by sserrata** [comment]
We might change/reword the support section in v2.0.0 and/or provide a way for users to define a custom template to override it.
