### ISSUE TITLE
Nullable objects not displayed as nullable in UI

### ISSUE THREAD

**Issue by Ryan5453** [PaloAltoNetworks/docusaurus-openapi-docs#448]
## Describe the bug

In the OpenAPI defintion, if there is a property in a schema with an `allOf` statement that only contains one schema, and the property is defined as nullable, the UI does not display it as nullable.

## Expected behavior

The UI should display that the object may be null, just like it does when it references another schema normally.

## Current behavior

It shows that the object will always be there, without showing it may be null.

## Steps to reproduce

1. Create an schema that contains a property with an `allOf` statement that only contains one schema, and the property is set to null.
    - [Example](https://api.flowery.pw/openapi.json) - The `LyricsResponse` schema contains a `task` property, which has an `allOf` statement that only contains a reference to the `TaskData` schema. The `task` property / the `TaskData` object is nullable.
2. Generate docs from that schema
3. Notice how it is not displayed as nullable

## Screenshots

<img width="200" alt="image" src="https://user-images.githubusercontent.com/50505980/220513364-069c1f5b-93f2-498d-9e20-95163f414ca0.png">
<img width="300" alt="image" src="https://user-images.githubusercontent.com/50505980/220513514-8d02b554-ca50-45bf-9aa0-6d733421f1b1.png">

## Your Environment

- Version used: 1.5.2
- Environment: Platform/Browser agonistic, issue resides in generating MDX file

**Comment by Ryan5453** [comment]
It seems like that this may be an issue with my OpenAPI specification. Pydantic is generating this automatically for me, so I have less control over it.

Looking into this more, it appears that when providing that the object is nullable to Pydantic via the Field constructor, it changes the OpenAPI reference from 

<img width="501" alt="image" src="https://user-images.githubusercontent.com/50505980/220524275-550597d8-45a2-49cb-831f-55516a6b5702.png">

to 

<img width="501" alt="image" src="https://user-images.githubusercontent.com/50505980/220524225-2328f19a-a9b4-4575-b2bc-5c16999ebb47.png">

I don't know why it does that, but I looked into the OpenAPI specification more, and it appears that this should still be valid since `allOf` 'validates the value against all the subschemas', and since there is only one value provided, it only validates against the one?

**Comment by sserrata** [comment]
Hi @Ryan5453, thanks for the work in debugging/investigating this. The `nullable` attribute is definitely getting left out prior to the `allOf` resolution. To support this, we would need to explicitly check for `nullable` and pass it along to `createEdges`.
