### ISSUE TITLE
Error : Hook useTabGroupChoice is called outside the <TabGroupChoiceProvider> on generating API docs

### ISSUE THREAD

**Issue by bhupendra1011** [PaloAltoNetworks/docusaurus-openapi-docs#473]
## Issue:  Hook useTabGroupChoice is called outside the <TabGroupChoiceProvider>. 

On generating docs from **openAPI** spec (.yaml) file , and configuring docusaurus.config  as below : 
![image](https://user-images.githubusercontent.com/5452261/222340068-b623370c-1636-4b02-acdf-8166700e5953.png)
API mdx files are geting generated on running : ` docusaurus gen-api-docs all` , but when the server is started :  getting error 

## Expected behavior

Docs should get rendered.

## Current behavior
<img width="670" alt="image" src="https://user-images.githubusercontent.com/5452261/222342964-e17a6bbc-2c44-46bf-b4b1-124db1ff9dd5.png">

## Steps to reproduce

1.
2.
3.
4.

## Your Environment

Node  v16.15.0
"@docusaurus/core": "2.0.0-beta.21",
- Version used:
- Environment name and version (e.g. Chrome 59, node.js 5.4, python 3.7.3):
- Operating System and version (desktop or mobile):
- Link to your project:

**Comment by sserrata** [comment]
Hi @bhupendra1011, `2.0.0-beta.21` is no longer supported by this plugin. For version `1.6.1` you'll need Docusaurus `>=2.0.1 <2.3.0` installed. We're working on bringing support for `2.3.0` which we hope to have available soon.
