### ISSUE TITLE
groupPathsBy none

### ISSUE THREAD

**Issue by tikolakin** [PaloAltoNetworks/docusaurus-openapi-docs#478]
### Is your feature request related to a problem?

Currently, a navigation sidebar only supports grouping [by tags](https://github.com/PaloAltoNetworks/docusaurus-openapi-docs#config). Alternatively, when `groupPathsBy` is not set - no sidebar is shown. 
This grouping by tag is not always desired and sometimes there is a need to just list endpoints 

### Describe the solution you'd like

provide support for `groupPathsBy: 'none'` which will disable grouping endpoint by tag but still will render a sidebar

### Describe alternatives you've considered

Alternatively, when `groupPathsBy` is not provided then no grouping will happen but the sidebar will be shown.

**Comment by sserrata** [comment]
Hi @tikolakin, if you don't pass any `sidebarOptions` then you can still use Docusaurus `autogenerated` sidebars to create a sidebar from the output.

**Comment by tikolakin** [comment]
Hi @sserrata 
Thanks for the hint 👍🏻 , indeed it work in the way we needed.
I will just leave a reference to docusaurus docs here https://docusaurus.io/docs/2.2.0/sidebar/autogenerated
