### ISSUE TITLE
Double scrollbars in response block

### ISSUE THREAD

**Issue by Woozl** [PaloAltoNetworks/docusaurus-openapi-docs#496]
## Describe the bug

Double scrollbars show up in the response block. This is essentially a duplicate of #416 which was resolved by #417, but in the response block, which I didn't notice when I fixed it in the language code block

## Expected behavior

One set of scrollbars

## Current behavior

Two sets of scrollbars makes it difficult to navigate the response JSON.

## Possible solution

Reverting the max-width/max-height on specific codeblocks, as in #417, or removing the top level styles [here](https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/blob/767cb952ac9dbcd9ad48e15f362eb79754b080f6/packages/docusaurus-theme-openapi-docs/src/theme/styles.css#L160-L164), which should prevent any future cases of this bug popping up.

## Steps to reproduce

Send request which results in JSON response wider than max-width of 600px, or taller than 500px.

## Screenshots

https://user-images.githubusercontent.com/16181779/225049939-cc0c5784-01e4-4ede-930f-cf6d2e4dc1be.mov

## Your Environment

- Version used:
Version used: v1.6.1
Environment name and version: Chrome Version 108.0.5359.124 (arm64)
Operating System and version (desktop or mobile): Mac M1

**Comment by sserrata** [comment]
Thanks @Woozl, we'll get these fixed

**Comment by sserrata** [comment]
Hi @Woozl, I opened the following PR which removes the redundant code block styles. Since I am unable to reproduce the issue on my Mac or Windows VM I was hoping you could help test. Thanks!

Preview: https://docusaurus-openapi-36b86--pr504-zc3wnf16.web.app/
