### ISSUE TITLE
Is there a support to add powershell language in API sample code gen

### ISSUE THREAD

**Issue by JnaneshD05** [PaloAltoNetworks/docusaurus-openapi-docs#499]
## Describe the bug

Need help in configuring if there is a support to add powershell also in the request sample code generator. 

## Expected behavior
Along with python , ruby, C# , need Powershell in the sample code generator

## Steps to reproduce

1.
2.
3.
4.

## Your Environment

- Version used:
- Environment name and version (e.g. Chrome 59, node.js 5.4, python 3.7.3):
- Operating System and version (desktop or mobile):
- Link to your project:

**Comment by JnaneshD05** [comment]
Thank You for the response!

**Comment by sserrata** [comment]
Available to test in canary release `0.0.0-598`

**Comment by JnaneshD05** [comment]
Thank you for the support. Would you mind helping out with regard to a command. 
gen-api-docs:version [options] <id:version>

I am finding difficulty to understand what is version here. I use docusaurus docs:version <version> . This works fine. But the abve command throws some error related to destructuring of parent.
