### ISSUE TITLE
Error when building project 

### ISSUE THREAD

**Issue by cryptodam** [PaloAltoNetworks/docusaurus-openapi-docs#501]
## Describe the bug

I tried several version of docusaurus and the plugin and I always face the same issue. I can yarn start my website properly but when I try to build I face this error:
ERROR] Unable to build website for locale en.
[ERROR] Error: Failed to compile with errors.
    at /Users/damienribault/git/docusaurus/my-website/node_modules/@docusaurus/core/lib/webpack/utils.js:180:24
    at /Users/damienribault/git/docusaurus/my-website/node_modules/webpack/lib/MultiCompiler.js:554:14
    at processQueueWorker (/Users/damienribault/git/docusaurus/my-website/node_modules/webpack/lib/MultiCompiler.js:491:6)
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)

## Expected behavior

No error when building

## Current behavior

ERROR] Unable to build website for locale en.
[ERROR] Error: Failed to compile with errors.
    at /Users/damienribault/git/docusaurus/my-website/node_modules/@docusaurus/core/lib/webpack/utils.js:180:24
    at /Users/damienribault/git/docusaurus/my-website/node_modules/webpack/lib/MultiCompiler.js:554:14
    at processQueueWorker (/Users/damienribault/git/docusaurus/my-website/node_modules/webpack/lib/MultiCompiler.js:491:6)
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)

## Steps to reproduce

1. Setup a docusaurus project on a mac
2. Add openapi plugin an theme
3. Use the openapi docusaurus.config.js file which is in the readme. 
4. Manage to yarn start
5. Can' yarn build without the error

## Your Environment

- Version used:
- I tried with several version of node/docusaurus (2.2.0 and 2.3.1) and plugin (1.6.1 then the brand new 2.2.0.beta)
- Apple M1 Pro on ventura 13
- Link to your project:

**Comment by johannesreichard** [comment]
same here, sitting in front of the exact same error, very similar setup, macbook, ventura etc.

**Comment by cryptodam** [comment]
Hello sserrata,
Thanks for the help.
I tried with node/16.19.1 and v2.2.0 of docusaurus and v1.6.1 of the plugin
   and I tried with node/18.14.2 and v2.3.1 of docusaurus and v2.0.0.beta of the plugin

I can t share my openapi publicly but it seems related to it as I have tried with other openapi yaml files and it wasnnot giving the same error. Do you know any specific I should look at. 
I noticed that some of my "send API Request" where giving connection failure when i use yarn start, maybe related to this

**Comment by cryptodam** [comment]
Thanjs Sserrata. I did use spectral and was able to fix some errors. I think the one that created the issue was the response description like that:

      responses:
        '200':
          description: xxx.
          content:
            application/json:
              schema:
                $ref: './schemas/responses/yyy.yaml'
              examples:
                cURL (example Curl): 
                  value:
                    $ref: './examples/responses/yyy.yaml'
                Python (Python example): 
                  value: {'error': [], 'result': {'descr': {'yyy': 'aaa'}, 'id': ['zzzz']}}
