### ISSUE TITLE
Usage of Template config option is not mentioned 

### ISSUE THREAD

**Issue by bhupendra1011** [PaloAltoNetworks/docusaurus-openapi-docs#503]
## Documentation link
https://docusaurus-openapi.tryingpan.dev/#config

## Describe the problem

There is no info or example how to use the template option for the plugin configs :
<img width="907" alt="image" src="https://user-images.githubusercontent.com/5452261/225536387-74e3f77e-65ea-4ae0-841c-e2e10aefc165.png">

Is it possible to wrap the contents generated from plugin with a custom defined in **template** config option.

## Suggested fix
To include demo/ docs to show what format of template should  look like

**Comment by sserrata** [comment]
Hi @bhupendra1011, the template option is used in the demo site:

Template: https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/blob/main/demo/api.mustache
Config: https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/blob/main/demo/docusaurus.config.js#L233

Basically, it allows for overriding the frontmatter and injecting some MDX before or after the generated content.
