### ISSUE TITLE
Hook useDoc is called outside the <DocProvider>.

### ISSUE THREAD

**Issue by RmallaBuckzy** [PaloAltoNetworks/docusaurus-openapi-docs#505]
When i am running the project, the project is getting the following error:

![image](https://user-images.githubusercontent.com/88499311/225818176-4dea4e47-f5d6-4df6-b706-8e9905ae95a5.png)
I am facing this issue mainly in windows systems but not in mac.

In Windows systems:
Installing the plugins, themes to the docusaurus project and configuring the docusaurus-config.js and sidebar.js files as given in the documentation.
Unable to start the project with the git template on my windows system.

In Mac systems:
The pages are appearing perfectly when i installed with template from git.

**Comment by sserrata** [comment]
Looks like a mismatch between Docusaurus and plugin versions. You may need to pin versions to avoid this.

**Comment by RmallaBuckzy** [comment]
How to pin the versions for Docusaurus and plugins?

What are the recommended versions regarding the same.

**Comment by rojakcoder** [comment]
I had this error before as well.

I was using Docusaurus v2.3.1 - you need to use the beta version of `docusaurus-openapi-docs` with v2.3.x of Docusaurus.

**Comment by sserrata** [comment]
@RmallaBuckzy any updates on this issue?

**Comment by fforootd** [comment]
I saw this too with 2.3.1 and the beta version of this plugin (i did not pin any deps with a resolution)

Btw. really nice job this plugin @zitadel we really like it 🙇

**Comment by bensch777** [comment]
Have the same issue and not able to fix it.

Versions:
- docusaurus: 2.4.0
- docusaurus-plugin-openapi-docs: 1.7.0
- docusaurus-theme-openapi-docs: 1.7.0

**Comment by Gijsdeman** [comment]
I have this issue as well when using docusaurus v2.4.0. By using the following configuration it works on my end.

- "@docusaurus/core": ">=2.0.1 <2.3.0",
- "@docusaurus/preset-classic": ">=2.0.1 <2.3.0",
- "docusaurus-plugin-openapi-docs": "^1.7.0",

**Comment by Taylor123** [comment]
> 

This stems from mismatched docusaurus and `docusaurus-theme-openapi-docs` versions.

Update with `yarn add docusaurus-theme-openapi-docs@next` to install the latest beta version.

**Comment by slorber** [comment]
Docusaurus maintainer here 👋 

It's unfortunate that this plugin had to break on Docusaurus v2.x.

We can't fix the past but let me know if I can do something to ensure it does not break in the future on minor version releases. For example, is this plugin v2 only relying to public apis of Docusaurus, or should we expose additional public apis?
