### ISSUE TITLE
Introduction pages generated when no description provided in openapi info section

### ISSUE THREAD

**Issue by mattgrosvenor-fs** [PaloAltoNetworks/docusaurus-openapi-docs#538]
## Describe the bug

Introduction pages are generated from open api docs even when they don't have a description.

## Expected behavior

An introduction page should only be generated when a description is set.

## Current behavior

An introduction page is being generated when there is either a title or description.

## Possible solution

This [line](https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/blob/7a2e961f9d28ed1cc5489e69c51a202eceae4518/packages/docusaurus-plugin-openapi-docs/src/openapi/openapi.ts#L91) was modified in this [PR](https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/pull/444) although the PR has nothing to do with the introduction change. The extra conditional `|| openapiData.info.title` should be removed or documented.

## Steps to reproduce

1. Have an open api compatible file with an info section without a description configured as a `specPath` in `docusaurus.config.js`.
```proto
  "info": {
    "title": "some/path/to/a/proto/file.proto",
    "version": "version not set"
  },
  ```
2. Run `docusaurus gen-api-docs`
3.  See a file generated `some-path-to-a-proto-file-proto.info.mdx`

## Context

I'm in the process of updating from version `1.5.1` to `1.7.0` and a bunch of extra introduction pages were generated. There is nothing in the release notes to indicate this change.

**Comment by sserrata** [comment]
Hi @mattgrosvenor-fs, the change was introduced in https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/pull/444 since the `SecuritySchemes` are reliant/dependent on the `info` page. It probably should have been a separate PR but it was blocking the changes needed to extend support for all security schemes. 

Outside of the undocumented/unexpected behavior, what is the rationale for not wanting the `info` docs to be generated? With or without a description, they could still be helpful for documenting help/support/contact and security schemes. Thanks!

**Comment by mattgrosvenor-fs** [comment]
I have multiple swagger files being used to generate documentation, having nearly identical `info` docs for each for each is unnecessary and a little redundant. Help and security schemes is documented in another section as it applies to everything. Would it be possible to add an option to not generate the `info` doc?

**Comment by sserrata** [comment]
There's currently no way to not generate them. You can delete them in post, including from the generated `sidebar.js` files.

Are you bringing all the API docs under the same sidebar? If you are, you can also try using `categoryLinkSource: "info"` to embed the `info` docs as category links.
