### ISSUE TITLE
Right sidebar doesn't load for `build`

### ISSUE THREAD

**Issue by xgp** [PaloAltoNetworks/docusaurus-openapi-docs#558]
## Describe the bug

When I am running docusaurus with `yarn start`, the right sidebar (request params, auth, code samples) loads. When I use `yarn build`  and serve as a static site, it stays in a "Loading..." state.

## Expected behavior

The right sidebar should load.

## Current behavior

it stays in a "Loading..." state

## Possible solution

Unknown. Maybe this error is relevant?
![image](https://user-images.githubusercontent.com/244253/233733490-d9c05156-c2b2-4cb7-8d3c-47831428beda.png)

## Steps to reproduce

1. use this repo https://github.com/p2-inc/phasetwo-docs
2. run `yarn build`
3. serve the resulting files from a static webserver
4. for example: https://phasetwo.io/api/get-organizations/

## Screenshots

![image](https://user-images.githubusercontent.com/244253/233733747-4b843142-0c55-4912-becf-cd2fda694a0b.png)

## Your Environment

- Version used: 1.7.0

**Comment by sserrata** [comment]
Hi @xgp, it's possible you have a version mismatch/incompatibility between the plugin and Docusaurus. Please review the compatibility table in the README/docs.

**Comment by xgp** [comment]
Hi @sserrata Thanks for the message. I was in the compatibility table ranges (docusaurus `2.2.0` and plugin version `1.7.0`). However, I updated to use the same versions ranges as the `demo/` project, and it worked. Not sure what the difference was, but maybe it will help someone with the same problem.
