### ISSUE TITLE
How to avoid generating docs for few API defs

### ISSUE THREAD

**Issue by JnaneshD05** [PaloAltoNetworks/docusaurus-openapi-docs#562]
## Describe the bug

I have a requirement where I need to avoid documenting every API def in the OpenAPI spec yaml. Is there a way we can achieve this in docusaurus ?

## Expected behavior

To be able to customize the generation of API docs.

## Context

To handle certain APIs hidden from docs.

## Your Environment

- Version used:
- Environment name and version (e.g. Chrome 59, node.js 5.4, python 3.7.3):
- Operating System and version (desktop or mobile):
- Link to your project:

**Comment by JnaneshD05** [comment]
Hi Team, Can we please get help regarding this ?

**Comment by cblanc** [comment]
You can exclude them by configuring `exclude` on this plugin: https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-content-docs
