### ISSUE TITLE
Postman plugin and theme

### ISSUE THREAD

**Issue by gii-pan** [PaloAltoNetworks/docusaurus-openapi-docs#564]
## Describe the bug

The section of postman plugin is without the theme and some of our documentation didn't get the postman code in mdx.

## Expected behavior

The postman plugin should display the theme in all languages ​​as shown in the [demo version of the website](https://docusaurus-openapi.tryingpan.dev/petstore/add-pet) and the url should be automatically completed.

## Current behavior

The Ruby, C#, PHP, Java and Powershell ​​are without the default theme and present the code in black and white.
Some mdx files generated by the plugin do not contain the code that postman should manage.

## Steps to reproduce

[Live example](https://docs-api.oobj.com.br/docs/api/oobj/buscar-url-baseconhecimento-using-get)

1. Install Docusaurus;
2. Install and config the plugin/theme of Open Api;
3. Generate the docs;
4. Start Docusaurus.

## Screenshots

![postman](https://user-images.githubusercontent.com/64155751/235789800-09b9a85d-2d58-4c82-b7b1-6b9b44f7a720.gif)

![requisicao](https://user-images.githubusercontent.com/64155751/235790940-fddebc03-dd76-4c74-860c-cea9124bd551.gif)

## Context

We need the requests working for the users, as well as the styling for a homogeneous look.

## Your Environment

- Version used: I tried with v1.6.1, v1.7.2 and v2.0.0;
- Environment name and version: Microsoft Edge, node.js 18.1.0, python 3.10.6;
- Operating System and version: desktop;
- Link to your project: private.

**Comment by gii-pan** [comment]
I found out today that the issue with the postman code not being generated is due to the (.pdf ) in some endpoints like the one below:

/api/empresas/docs/{ambiente}/{codModelo}/{cnpjInteressado}/{ano}/{serie}/{numero}.pdf

What could I do?  How to proceed? 

The issue with the theme not being applied(first gif above) still persists.

**Comment by sserrata** [comment]
Hi @gii-pan, for the languages missing the theme/highlighting, have you already defined them in `additionalLanguages`?

Example: https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/blob/main/demo/docusaurus.config.js#L139

Concerning the `.pdf` issue, can you explain why those operations/paths end in a file extension? I am not familiar with that use case. Thanks!

**Comment by artushin** [comment]
@gii-pan Did you ever figure out a solution or workaround to your .pdf issue?
