### ISSUE TITLE
2.0.0-beta.3 - Authorization link not respecting docs.routeBasePath

### ISSUE THREAD

**Issue by IanVS** [PaloAltoNetworks/docusaurus-openapi-docs#572]
## Describe the bug

I have the following config:

```ts
presets: [
    [
      'classic',
      ({
        docs: {
          routeBasePath: '/', // Serve the docs at the site's root
```

Which means that my docs live at the root of the site, not under `/docs`.

But when I click on the new authorization link, I get a 404 because it includes `/docs` in the URL.

<img width="229" alt="image" src="https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/assets/4616705/6c7ed82a-3bc6-44fe-bfb4-f92e538c181e">

## Expected behavior

The link should be constructed correctly, using `docs.routeBasePath`.

## Current behavior

404

## Steps to reproduce

1.
2.
3.
4.

## Your Environment

- Version used: 2.0.0-beta.3
- Environment name and version (e.g. Chrome 59, node.js 5.4, python 3.7.3):
- Operating System and version (desktop or mobile):
- Link to your project:

**Comment by sserrata** [comment]
Hi @IanVS, the base path is supposed to be resolved via the `docsPluginId` option and should factor in `routeBasePath` when constructing those links. Can you share your plugin config?
