### ISSUE TITLE
[minor] allOf with enums in query renders as an object, instead of all possible values listed

### ISSUE THREAD

**Issue by Ifropc** [PaloAltoNetworks/docusaurus-openapi-docs#574]
## Describe the bug

Having a query element being intersection of 2 enums renders in as an object, instead of all available options.

## Expected behavior

(Using Swagger editor)

![image](https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/assets/62526399/010fd13f-0fa6-4cb9-a06a-4d15f8be7b7b)

(Using ReDoc)

![image](https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/assets/62526399/89fd2247-c487-45d9-9a6c-7ed4ea962418)

## Current behavior

(Using this plugin, v1.7.2)

![image](https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/assets/62526399/8507a49b-d5dd-42b8-9972-33a0817916cc)

## Possible solution

N/A

## Steps to reproduce

You can check the yml file [here](https://github.com/stellar/stellar-docs/blob/eda21aea108dd670bc0504d2255fc2a4f55240df/openapi/ap/bundled.yml)
ReDoc: [link](https://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/stellar/stellar-docs/eda21aea108dd670bc0504d2255fc2a4f55240df/openapi/ap/bundled.yml#tag/SEP-24/operation/getTransactions)
And the preview is hosted [here](https://developers-pr140.previews.kube001.services.stellar-ops.com/ap_api/resources/get-transactions)
(Can also clone the branch and `yarn start` locally)

## Context

I need to manually define a new enum, that has all possible values in it in a unified way  

## Your Environment

All versions, etc. are available in the [package.json file](https://github.com/stellar/stellar-docs/blob/eda21aea108dd670bc0504d2255fc2a4f55240df/package.json)

**Comment by sserrata** [comment]
exception is thrown by `json-schema-merge-allof` library. Please open issue with their maintainers.
