### ISSUE TITLE
Finding and verifying api issues: Docusaurus server-side rendering could not render static page with path

### ISSUE THREAD

**Issue by jeffpascal** [PaloAltoNetworks/docusaurus-openapi-docs#586]
## Describe the bug

I'm experiencing issues with API documentation while adding a large API to a Docusaurus project. When I try to build the project, I receive multiple errors related to server-side rendering. Although Redocly OpenAPI CLI only reports warnings for these API endpoints, they fail to build in Docusaurus.

## Expected behavior

I expect the API documentation to build successfully in Docusaurus without any errors.

## Current behavior

While building the API documentation inside Docusaurus, the following errors occur:

[ERROR] Docusaurus server-side rendering could not render static page with path /docs/api_versioned/dev/endpoint

## Possible solution

I'm seeking a reliable way to identify and fix these issues with API documentation, including a method to validate the correctness of an API before building the documentation.

## Steps to reproduce

I first run Redocly OpenAPI CLI to check the API for any issues.
Although it only reports warnings for these endpoints, they do not build in Docusaurus.
I then try to build the Docusaurus project, which throws the aforementioned errors.

## Context

These issues are preventing me from correctly adding a large API to our Docusaurus-based API documentation portal. It's critical for us to have a fully functional and reliable API portal for both internal and external users.

## Your Environment

- Version used:  "^1.4.7",
- Environment name and version (e.g. Chrome 59, node.js 5.4, python 3.7.3): 18.13.0
- Operating System and version (desktop or mobile): windows 10
- Link to your project: N/A

**Comment by sserrata** [comment]
Hi @jeffpascal, what version of `docusaurus-openapi-docs` are you attempting to use? Docusaurus version?

Does your OpenAPI spec pass a basic linter test? I recommend a tool like spectral for linting - they also have a nice vscode extension available.

**Comment by SirPhemmiey** [comment]
Hi @sserrata i am also having the same issue
