### ISSUE TITLE
How can I customize the by adding the server section in the info.mdx

### ISSUE THREAD

**Issue by JnaneshD05** [PaloAltoNetworks/docusaurus-openapi-docs#590]
Hi, 
I need help on this requirment. I want the Server Section of the Api Panel to be shown in the info section page as well. 
I imported Server component and tried displaying it but i am not successful. Could you please guide me?

**Comment by sserrata** [comment]
Hi @JnaneshD05 unfortunately this is not supported by the existing Server component. My advice would be to explore creating a custom component for this purpose that can accept the `api` frontmatter as a prop.
