### ISSUE TITLE
MDX compilation fails with Docusaurus v3

### ISSUE THREAD

**Issue by TheCatLady** [PaloAltoNetworks/docusaurus-openapi-docs#591]
## Describe the bug

```
Error: MDX compilation failed for file "<redacted>"
Cause: Expected a closing tag for `<div>` (30:1951-30:1956) before the end of `paragraph`
Details:
{
  "name": "30:1-30:1956",
  "message": "Expected a closing tag for `<div>` (30:1951-30:1956) before the end of `paragraph`",
  "reason": "Expected a closing tag for `<div>` (30:1951-30:1956) before the end of `paragraph`",
  "line": 30,
  "column": 1,
  "position": {
    "start": {
      "line": 30,
      "column": 1,
      "offset": 1584,
      "_index": 0,
      "_bufferIndex": 0
    },
    "end": {
      "line": 30,
      "column": 1956,
      "offset": 3539,
      "_index": 1,
      "_bufferIndex": -1
    }
  },
  "source": "mdast-util-mdx-jsx",
  "ruleId": "end-tag-mismatch"
}
```

## Expected behavior

Successful compilation

## Current behavior

MDX compilation fails

## Steps to reproduce

1. Update Docusaurus package versions in `package.json` to [`3.0.0-alpha.0`](https://github.com/facebook/docusaurus/releases/tag/v3.0.0-alpha.0)
2. `yarn`
3. `yarn build`

## Context

Just testing the brand-new [Docusaurus v3 alpha](https://github.com/facebook/docusaurus/releases/tag/v3.0.0-alpha.0) for now to find potential migration issues, but would like to upgrade later when v3 enters beta or has a stable release.

## Your Environment

- Version used: `0.0.0-beta.660`

**Comment by TheCatLady** [comment]
Nevermind--this seems to be an issue introduced outside of this plugin. Closing 😄

**Comment by robbieaverill** [comment]
FWIW - I was seeing this problem with Docusaurus 3.4.0 and docusaurus-openapi-docs ~2.0.0. Updating to ~3.0.0-beta resolved the problem for me.
