### ISSUE TITLE
Token fetching

### ISSUE THREAD

**Issue by drwelby** [PaloAltoNetworks/docusaurus-openapi-docs#594]
### Is your feature request related to a problem?

Unless my spec isn't rendering right, it looks like if an endpoint, for instance, uses Oauth2 password flow, the request parameters box has an input for a bearer token but no way to fetch that token using the information in the OpenAPI spec. 

### Describe the solution you'd like

Ideally there should be a way fetch a token through the page UI. If the state can be preserved between pages, having the process be an "Authenticate Me" user flow and have the token persist and populate across different endpoints would be even more convenient .  

### Describe alternatives you've considered

While token operations don't fit the REST model of OpenAPI very well, we can make and generate documentation for a "Get Token" endpoint and the user can copy and paste their token for the response. However this is more awkward that it should be.

**Comment by sserrata** [comment]
Hi @drwelby, IMO, the ideal approach would be to leverage something like OIDC to obtain a token after a user signs in, that could then be used to send authenticated requests to the API.

Unfortunately, token fetching is beyond the current scope of this project but we are definitely open to PRs/contributions.
