### ISSUE TITLE
More detail needed to get plugin working

### ISSUE THREAD

**Issue by jacknevitt** [PaloAltoNetworks/docusaurus-openapi-docs#604]
## Documentation link

https://github.com/PaloAltoNetworks/docusaurus-openapi-docs#configuring-docusaurusconfigjs-plugin-and-theme-usage

## Describe the problem

The guide does not sufficiently describe how to get the plugin working with a docusaurus project. Using the provided code examples does not build any pages.

I have created a new docusaurus project with `npx create-docusaurus@latest my-website classic --typescript`.
I have installed `docusaurus-plugin-openapi-docs` and `docusaurus-theme-openapi-docs` (v1.7.3).
I have downgraded `@docusaurus/core` and  `@docusaurus/preset-classic` to v2.2.x as v2.4.0 is not supported by the plugin.
I have used the code recommended for the `docusaurus.config.js` and copied the `petstore.yaml` file to the project.

## Suggested fix

Include more detail in the installation guide to get the plugin working with a typical docusaurus project.

**Comment by PeterMerkert** [comment]
Hi @jacknevitt , I have also trouble getting the project up and running with latest Docusaurus. From your repository, I cannot see the usage of "docusaurus-theme-openapi-docs" or anything from this repo here. Can you ensure to submit your sample?

**Comment by bonimart** [comment]
I'm having a similar issue (also downgraded docusaurus to 2.2.0 and installed v1.7.3). When I run `docusaurus start`, everything seems alright, but when I run `docusaurus build` I get the following  errors:
```
export 'toString' (imported as 'toString') was not found in 'docusaurus-theme-openapi-docs/lib/markdown/utils
export 'guard' (imported as 'guard') was not found in 'docusaurus-theme-openapi-docs/lib/markdown/utils
```

**Comment by jacknevitt** [comment]
My apologies @PeterMerkert, I had accidentally overwritten the repo with redocusaurus.

**Comment by sserrata** [comment]
Will update docs coinciding with next stable releases.
