### ISSUE TITLE
[ERROR]     Unknown command gen-api-docs.

### ISSUE THREAD

**Issue by aperture** [PaloAltoNetworks/docusaurus-openapi-docs#610]
## Describe the bug

when i try and run `pnpm docusaurus gen-api-docs all`  I get an error saying [ERROR]     Unknown command gen-api-docs.

## Expected behavior

Commands should be added to docusaurus 

## Current behavior

Commands weren't added to docusaurus 

## Steps to reproduce

1. pnpx create-docusaurus@2.2.0 my-docs classic
2. cd my-docs/
3. pnpm add docusaurus-plugin-openapi-docs
4.pnpm add docusaurus-theme-openapi-docs
5. configure docusaurus config as described in the installation instructions
6. pnpm docusaurus gen-api-docs all

## Screenshots
<img width="925" alt="Screenshot 2023-08-10 at 7 01 19 PM" src="https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/assets/127937/a3e03bc6-3a36-4b64-a67e-9e586c547b82">

## Your Environment
Macbook pro m1

- Version used:
- Environment name and version (e.g. Chrome 59, node.js 5.4, python 3.7.3):
- Operating System and version (desktop or mobile):
- Link to your project:

**Comment by sserrata** [comment]
Hi @aperture, I was able to reproduce this issue. It seems the method we are using to `extendCli` isn't supported by `pnpm`. Do you know if any similar/related issues/bugs have been reported to Docusaurus?

**Comment by aperture** [comment]
Not that I'm aware of, I just switched my project over to yarn and
everything seemed to work smoothly from there :)
