### ISSUE TITLE
Request of type FormData does not work in DemoPanel

### ISSUE THREAD

**Issue by jk8** [PaloAltoNetworks/docusaurus-openapi-docs#618]
## Describe the bug

Our API uses a request with a **FormData** content type to send media files, and I noticed that the "Send API Request" button (in the API Demo panel) doesn't work properly for those requests. In the browser's network panel, I can see that the request payload only contains an initial delimiter (eg `------WebKitFormBoundarytopELwrKuCYnvZxH--`) but no content follows.

## Expected behavior

The content of the FormData request should be properly serialized.

## Current behavior

The content of the FormData request is incomplete. It only contains the initial delimiter, but nothing else.

## Possible solution

I found 2 problems in `makeRequest.ts` source:
1. The request body is initially serialized to JSON. This probably won't work for binaries. 
```
  const body = request.body?.toJSON();
```
2. The request has a `Content-Type` header set to `multipart/form-data` but does not contain a boundary separator. No need to set Content-Type - `fetch()` will set the correct content-type automatically.

I tried to solve this problem for my case here: https://github.com/jk8/docusaurus-openapi-docs/commit/796b32eca5c6ee3e4d1f80f8606211a58e784890

EDIT: ~I can't create PR because latest commit of `v2.0.0` branch does not work for me at this time and I can't test it.~

## Your Environment

- Version used: v2.0.0-beta.3
- Environment name and version: Chrome 116
- Operating System and version (desktop or mobile): Linux
- Link to your project: N/A

**Comment by jk8** [comment]
I tried again and it seems fine. I must have made some mistake last time. Sorry for the confusion. I have opened PR #625

**Comment by sserrata** [comment]
Hi @jk8, just checking in to see if the fix worked as expected before we close this issue

**Comment by jk8** [comment]
yes, it works well. Thank you. It can be closed.
