### ISSUE TITLE
OpenAPI 3.x Support

### ISSUE THREAD

**Issue by sheldonreddy** [PaloAltoNetworks/docusaurus-openapi-docs#619]
## Documentation link

[NPM Docs](https://www.npmjs.com/package/docusaurus-plugin-openapi-docs)
[Github Docs](https://github.com/PaloAltoNetworks/docusaurus-openapi-docs)

## Describe the problem

NPM and Github docs specify different versions for OpenAPI3.x support. 
It's confusing not knowing whether OAS3.1 is supported or not. 

## Suggested fix

Update docs for support OAS3.x versions

Also - please confirm if OAS 3.1 supported whilst fix is implemented?

**Comment by sserrata** [comment]
Hi @sheldonreddy, thanks for opening the issue. As of today, OpenAPI 3.1 is not supported. We will update the npm docs to reflect this.

**Comment by sheldonreddy** [comment]
Hey @sserrata 

No problem! Thanks for providing feedback. 
Cheers
