### ISSUE TITLE
Postman collection support

### ISSUE THREAD

**Issue by guptaashwanee** [PaloAltoNetworks/docusaurus-openapi-docs#630]
### Postman collection support
I would like to thanks for this wonderful API documentation tool. I have and almost a lot of people faced problems while converting postman collection to openapi specification.

This can be a very good feature to direct support of postman collection along with openapi.

**Comment by sserrata** [comment]
Hi @guptaashwanee I recommend submitting this FR to the maintainers of the postman libraries. Thanks!
