### ISSUE TITLE
Cloning Git template failed

### ISSUE THREAD

**Issue by andreslon** [PaloAltoNetworks/docusaurus-openapi-docs#632]
The cloning template provided in the documentation at https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/tree/main#installing-from-template seems to be broken. 

Even after trying different cloning options and forking the repository, the same error persists. 

Refer to the screenshot for more details.

![image](https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/assets/2242679/d1bfec77-91a6-415f-b261-64918ef10458)

**Comment by graham-fleming** [comment]
I also get the same error following documentation

https://github.com/PaloAltoNetworks/docusaurus-openapi-docs

```powershell
PS C:\Users\Documents> npx create-docusaurus@2.4.3 my-website --package-manager yarn
√ Select a template below... » Git repository
√ Enter a repository URL from GitHub, Bitbucket, GitLab, or any other public repo.
(e.g: https://github.com/ownerName/repoName.git) ... https://github.com/PaloAltoNetworks/docusaurus-template-openapi-docs.git
√ How should we clone this repo? » Copy: do a shallow clone, but do not create a git repo
[INFO] Creating new Docusaurus project...
fatal: could not create leading directories of ''C:\Users\Documents\my-website'': Invalid argument[ERROR] Cloning Git template failed!
```

**Comment by lxluxo23** [comment]
I had the same problem, I solved it using the WSL feature of windows, the error only occurs in windows.

**Comment by joaorodr84** [comment]
> I had the same problem, I solved it using the WSL feature of windows, the error only occurs in windows.

I tried with WSL and it still doesn't work.

Is there another solution to this?

**Comment by Praveencompro** [comment]
I facing the same problem. @lxluxo23 could you please share the detailed solution.
