### ISSUE TITLE
Missing boundary in Content-Type when multipart/form-data

### ISSUE THREAD

**Issue by AchrafAmil** [PaloAltoNetworks/docusaurus-openapi-docs#633]
## Describe the bug

The interactive Prism console for upload endpoint doesn't seem to make the right call for endpoints with content-type `multipart/form-data`

## Expected behavior

Expects the call made from the console to specify a `boundary`
(otherwise the server receiving the request fails with a legit `java.io.IOException: Failed to parse multipart: Content-Type's boundary parameter is missing`).

## Current behavior

The request it makes when hitting the "send api request" seems malformatted.

## Possible solution

Specify the boundary, e.g. `content-type: multipart/form-data; boundary=------WebKitFormBoundaryF6sSRjfPR0gJB7xK`

## Steps to reproduce

1. Go to https://docs.nabla.com/server/copilot-listen-from-file
2. (you don't care about having a working api key or even about specifying correct values for the rest of the fields)
3. Drag & drop a random file, and inspect the network request it makes.
4. The request body is multi-part and has a boundary but it's not specified in the content-type header.

## Screenshots

<img width="1797" alt="image" src="https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/assets/7039320/4deae3d1-b372-4523-82cf-b327cfd7710e">

![Untitled](https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/assets/7039320/f34e88b6-53a1-4871-a148-9ca4ab2a3dec)

## Your Environment

- Version used:
```json
    "@asyncapi/generator": "^1.10.9",
    "@docusaurus/core": "^2.4.1",
    "@docusaurus/preset-classic": "^2.4.1",
    "@mdx-js/react": "^1.6.22",
    "clsx": "^1.1.1",
    "docusaurus-plugin-openapi-docs": "^2.0.0-beta.3",
    "docusaurus-theme-openapi-docs": "^2.0.0-beta.3",
    "prism-react-renderer": "^1.3.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "html-loader": "^4.2.0"
```
- Environment name and version Chrome 117.0.5938.92 arm64
- Operating System and version: macOS Ventura 13.3.1 
- Link to your project: docs.nabla.com

**Comment by sserrata** [comment]
Hi @AchrafAmil, did #625 address your issue?

**Comment by AchrafAmil** [comment]
Thanks for sharing, I didn't know about #625.
Just upgraded to beta-4 to have it and it seems to fix the boundary issue:
<img width="693" alt="image" src="https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/assets/7039320/396065c3-146b-4c67-a773-1f0f7d41140c">

But it now doesn't include the json string item in the FormData (`request_parameters`).

As you can see in the screenshot the body doesn't include the `request_parameters` as it used to in the beta3.

<img width="1262" alt="image" src="https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/assets/7039320/0bffd848-bc1e-4a4e-ba7c-493751e4b346">

**Comment by AchrafAmil** [comment]
Tested with the new stable `2.0.0`:
```
    "@docusaurus/core": "^2.4.3",
    "@docusaurus/preset-classic": "^2.4.3",
    "docusaurus-plugin-openapi-docs": "^2.0.0",
    "docusaurus-theme-openapi-docs": "^2.0.0",
```
and I'm still facing the same problem as my previous comment (it does not include the json string item in the FormData).

@sserrata let me know if you need any more details on this

**Comment by sserrata** [comment]
Hi @AchrafAmil can you test again using `2.0.1`? Thanks!

**Comment by AchrafAmil** [comment]
Now it's working, wow awesome, thanks a lot! 🎉

(I'll let you decide if we can already close this issue, etc)

**Comment by AchrafAmil** [comment]
Though, now that I succeed in uploading a file I start hitting the 5 secs timeout pretty easily...
Is there any way to override the timeout other than the hardcode swizzle from #327 and #351 ? 🙏 

Because doing an eject swizzle for `ApiExplorer/Request` breaks my docs:
<img width="553" alt="image" src="https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/assets/7039320/26a340fc-55db-461c-8bf3-a7221b01d07e">
<img width="1096" alt="image" src="https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/assets/7039320/c5107351-a232-4b1d-a62d-32a2bf4374bb">
