### ISSUE TITLE
Improvements to webhook page layout

### ISSUE THREAD

**Issue by dredlong** [PaloAltoNetworks/docusaurus-openapi-docs#642]
Comments below relate to v2.0.0-beta4

### Is your feature request related to a problem?

We're currently implementing the plugin and would like to document our platform webhooks using the `x-webhooks` OpenApi spec (and then `webhooks` once v3.1 is supported). At the moment there are some issues with the way the doc page is generated:

- The `MethodEndpoint` component shows the API base URL with `webhook` concatenated on the end.
- The API request form still shows the base URL selector and the send request button, however webhooks would come from our platform to the user's endpoint rather than the other way around
- The generated code samples are shown, however they are all just an empty GET request to the base URL

### Describe the solution you'd like

- Just show a label like `EVENT: webhook` in the `MethodEndpoint` component
- Hide the generated code samples for method type = `event`
- For the sample form either:
1. Hide the Base URL field, submit button and response component
2. Allow the user to enter their own endpoint URL in a form input and send a test webhook request to it with the sample data

### Describe alternatives you've considered

Currently having a look at swizzling the component to achieve the above but thought it might be useful for others.

**Comment by sserrata** [comment]
Hi @dredlong, I opened #646 to incorporate your suggestions. Let me know what you think.
