### ISSUE TITLE
Our project is broken after ApiDemoPanel rename

### ISSUE THREAD

**Issue by shmichael** [PaloAltoNetworks/docusaurus-openapi-docs#655]
## Describe the bug

When upgrading 2.0.0.beta.3 -> 2.0.0.beta.5, our build is broken.

All our openapi endpoints produce errors similar to this:
```
Module not found: Error: Can't resolve '@theme/ApiDemoPanel/MethodEndpoint' in '[redacted]/docs/api/webhook'
Module not found: Error: Can't resolve '@theme/ApiDemoPanel/SecuritySchemes' in '[redacted]docs/api/webhook'
```
I believe this is the relevant change:
https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/pull/577

We do not reference ApiDemoPanel ourselves - it is all autogenerated from schema. In fact, I grepped all of our codebase for `demo` and `Demo` and there's nothing.

This fails both locally and on CI.

**Comment by sserrata** [comment]
Hi @shmichael, have you tried running `docusaurus clear`?

**Comment by rrosmus** [comment]
The same issue with `2.0.2` and docusaurus `2.4.0`.
`docusaurus clear` doesn't help.
