### ISSUE TITLE
^1.7.0 version stopped rendering Language tabs texts in API documentation

### ISSUE THREAD

**Issue by praveenmjoshi** [PaloAltoNetworks/docusaurus-openapi-docs#679]
## Description

We are using the plugin to convert openAPI spec in yaml files to markdown file to render as Documentation in our Docusaurus based application.

Pluggin stoped rendering texts under Language tab in API documentation

## Expected behavior

API documention expected to show variour language name above the API request code block 

## Steps to reproduce

1. Install a docusaurus template project
2. Modify dependencies to use Docusaurus >=2.0.1 <2.3.0 and docusaurus-plugin-openapi-docs ^1.7.0
3. Make changes to docusaurus.config.js file to use docusaurus-plugin-openapi-docs plugin
4. build and run the docusuarus project

## Screenshots

![image](https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/assets/18049731/d9bc745e-11d0-4be3-998c-92766ff84bd0)

# Below is the dependency list used in project

"dependencies": {
    "@docusaurus/core": ">=2.0.1 <2.3.0",
    "@docusaurus/preset-classic": ">=2.0.1 <2.3.0",
    "@easyops-cn/docusaurus-search-local": "^0.35.0",
    "@mdx-js/react": "^1.6.22",
    "@reduxjs/toolkit": "^1.9.5",
    "bootstrap": "^5.3.1",
    "clsx": "^1.1.1",
    "cors": "^2.8.5",
    "docusaurus-plugin-openapi-docs": "^1.7.0",
    "docusaurus-theme-openapi-docs": "^1.7.0",
    "docusaurus2-dotenv": "^1.4.0",
    "dotenv": "^16.3.1",
    "env-cmd": "^10.1.0",
    "express": "^4.18.2",
    "js-cookie": "^3.0.5",
    "lodash": "^4.17.21",
    "pm2": "^5.3.0",
    "prism-react-renderer": "^1.3.1",
    "react": "^17.0.2",
    "react-bootstrap": "^2.8.0",
    "react-dom": "^17.0.2",
    "react-redux": "^8.1.1",
    "react-router-dom": "^6.14.2",
    "redux": "^4.2.1"
  },

**Comment by sserrata** [comment]
Hi @praveenmjoshi if you're still experiencing this problem please open a new issue along with a link to a reproduction repo. Thanks!
