### ISSUE TITLE
Frontmatter api prop compression is nondeterministic

### ISSUE THREAD

**Issue by TheCatLady** [PaloAltoNetworks/docusaurus-openapi-docs#692]
## Describe the bug

On each `gen-api-docs` run, the frontmatter `api` prop changes.

## Expected behavior

The frontmatter `api` prop has consistent output for a given input.

## Current behavior

See someengineering/resoto.com#939, a pull request created by CI. There were no changes to the API spec.

## Possible solution

Use a deterministic algorithm for compression.

## Steps to reproduce

1. Generate API docs from the following specs: https://github.com/someengineering/resoto.com/tree/main/openapi
2. Regenerate and notice changed frontmatter.

## Context

This issue makes it difficult to review pull requests, as actual changes to the API spec/docs are difficult to find within all of the frontmatter changes.

## Your Environment

- Version used: `3.0.0-beta.4`
- Link to your project: https://github.com/someengineering/resoto.com

**Comment by sserrata** [comment]
Hi @TheCatLady, thanks for reporting, I can see how this is indeed an issue. We don't see it on pan.dev because we chose not to check-in generated files. I'll investigate to see if there's a way to make compression deterministic or explore adding the option to disable/enable compression.

**Comment by sserrata** [comment]
Hi @TheCatLady , sorry for overdue follow up on this...after digging in, it appears the difference may be due to difference in OS between local development machine and CI. That said, I'm looking to add a `disableCompression` plugin option to let users override the default behavior.

**Comment by sserrata** [comment]
As mentioned in #819 adding an `example` or `examples` to the `date-time` properties should prevent the autogenerated value from appearing.
