### ISSUE TITLE
Support for custom code samples via `x-codeSamples`

### ISSUE THREAD

**Issue by rattrayalex** [PaloAltoNetworks/docusaurus-openapi-docs#712]
### Is your feature request related to a problem?

Yes, I would like docs to render with snippets that show use of an API's custom-built SDKs, rather than generic http requests. This is what Stripe does.

### Describe the solution you'd like

If `x-codeSamples` is present, as with redocly, render the code present there rather than the code that would be generated by default.

### Describe alternatives you've considered

n/a

### Additional context

Previously discussed at https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/issues/153

I might be willing to fund a PR for this if it would be accepted. Please share any requirements for it.

**Comment by rattrayalex** [comment]
@sserrata would you accept a PR adding this?

**Comment by Mikescops** [comment]
Hello, I'm raising this issue too, it's an important need for our developers to read custom values from the interface.

**Comment by sserrata** [comment]
Addressed in:

#697
#701 
#706 
#707
