### ISSUE TITLE
Using $ref for primitive types erases the field type

### ISSUE THREAD

**Issue by AchrafAmil** [PaloAltoNetworks/docusaurus-openapi-docs#714]
## Documentation link

https://docs.nabla.com

## Describe the problem

When declaring a field like the following:

```yaml
email:
  $ref: "./shared/user_email.yaml"
```
While `user_email.yaml` is:
```yaml
type: string
description: Some long description for what a user email is used for etc etc etc... The same "email" field is reused in multiple endpoints (to share the description).
```

The output is:

<img width="481" alt="image" src="https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/assets/7039320/b178e8dc-bbf7-430e-bfbe-63908828c14c">

While I expect it to be (same as if the $ref was inlined):

<img width="485" alt="image" src="https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/assets/7039320/0d8dfe7f-e3d4-408b-91a7-fe7c2d007eec">

## Suggested fix

Instead of:
always assuming a $ref is referencing a complex object and thus giving its type a "name" (picking the file name is ok) while the rest of the doc-gen will indent the nested fields and everything is well-documented.
I suggest the doc-gen code to first checks if the referenced type is a primitive (string, boolean, or number) and if so lets its type name be the primitive type itself.

**Comment by cdstull** [comment]
I think this should be labeled as a bug. I'm having the same issue, any references to strings display the referenced name as the format instead of `string` as the format.

**Comment by AchrafAmil** [comment]
I agree but I can't change labels

**Comment by AchrafAmil** [comment]
upgraded to 2.1.3 and this is fixed: it shows `file name (primitive type)` (e.g. `user_email (string)`).
