### ISSUE TITLE
Free object ( additionalProperties: true ) in a oneOf did not render

### ISSUE THREAD

**Issue by marco10024** [PaloAltoNetworks/docusaurus-openapi-docs#721]
## Describe the bug

An error occurs when I have an entity whose property contains a oneOf referring to another entity of type free (additionalProperties to true)

Example : 
```
    {
        "$id": "User",
        "type": "object",
        "properties": {
            "id": {
                "type": "string",
                "format": "uuid"
            },
            "email": {
                "type": "string"
            },
            "parent": {
                "oneOf": [
                    {
                        "$ref": "FreeObject#"
                    },
                    {
                        "type": "null"
                    }
                ]
            }
      }
      
     {
        "$id": "FreeObject",
        "type": "object",
        "additionalProperties": true
      }
```

## Expected behavior

the FreeObject entity should in this case generate a `property name* any` at the rendering level :

<img width="204" alt="Capture d’écran 2024-02-07 à 09 30 50" src="https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/assets/6544513/0fe13d52-2b4e-410b-af97-99ab182df2e2">

## Current behavior

The command to generate the doc goes well ( docusaurus gen-api-docs all ). On the other hand, in this case it generates an empty `<SchemaTabs></SchemaTabs>` which then causes a build error

## Screenshots

<img width="347" alt="Capture d’écran 2024-02-07 à 09 36 32" src="https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/assets/6544513/b7d124dd-5157-4b1e-a810-79dc1a4bcb5c">

<img width="761" alt="Capture d’écran 2024-02-07 à 09 36 55" src="https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/assets/6544513/c7aa3390-3a78-4a82-94aa-2e9aa2efa59c">

## Your Environment

- Version used: 2.0.4 and docusaurus 2.4.3
- Environment name and version (e.g. Chrome 59, node.js 5.4, python 3.7.3): nodeJs 20
- Operating System and version (desktop or mobile): macOS
- Link to your project:

**Comment by sserrata** [comment]
Hi @marco10024, thanks for reporting. Seems like an edge case we didn't account for, i.e. a `oneOf/anyOf` with a nested `additionalProperties` object. I'll see if I can get to it or hopefully someone in the community can lend a hand.

**Comment by marco10024** [comment]
Hello @sserrata , thank you for your answer. yes it's a bit of a special case, I hope it will be easy to manage on your side. for the moment I patched this with a sed once the doc is generated if it can help other people in my case:

```
    "fix": "sed -i 's/<SchemaTabs><\\/SchemaTabs>/<div style={{\"marginLeft\":\"1rem\"}}><SchemaItem name={\"property name*\"} required={false} schemaName={\"any\"} qualifierMessage={undefined} schema={{\"type\":\"object\",\"additionalProperties\":true}} collapsible={false} discriminator={false}><\\/SchemaItem><\\/div>/g' ./docs/api/*.mdx",
    "generate-api-docs": "docusaurus gen-api-docs all && npm run fix",
```

**Comment by sserrata** [comment]
Hi @marco10024, I believe this issue has been resolved with recent changes. Much appreciated if you could test `0.0.0-730` canary release - please reopen this issue if needed. Thanks!
