### ISSUE TITLE
Enhanced Export Functionality for Local OpenAPI Files

### ISSUE THREAD

**Issue by hjhrwerv2423** [PaloAltoNetworks/docusaurus-openapi-docs#722]
I want the ability to specify a local YAML file in the `downloadUrl`, located at `/static/openapi.yaml` on my system. Currently, I lack this capability, so I'm using a workaround. I simply mention the path in the description section of `openapi.yaml`, and everything works. However, I would prefer to use the standard mechanism with an attractive 'export' button.

[Download openapi.yaml](/openapi.yaml)

### Is your feature request related to a problem?

No.

### Describe the solution you'd like

I seek a straightforward and standardized way to link to a local YAML file directly through the `downloadUrl` parameter. This method should enable users to download the file by clicking an 'export' button, enhancing user experience and maintaining a neat interface.

### Describe alternatives you've considered

As a temporary solution, I manually include the file path in the API documentation's description section, allowing users to access and download the file. However, this approach lacks the polish and ease of use that a dedicated export button would offer.

### Additional context

This feature request arises from the need for a more integrated and user-friendly method to share local YAML files with API consumers.

**Comment by sserrata** [comment]
Hi @hjhrwerv2423, we currently provide a helper HTML component specifically for this. You can demo it here: https://docusaurus-openapi.tryingpan.dev/petstore/swagger-petstore-yaml

You can enable it by specifying a `downloadUrl` like in this example: https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/blob/main/demo/docusaurus.config.js#L239. However, it has to be a URL, i.e. references to local files in the filesystem is not supported.
