### ISSUE TITLE
Request not updating when switching between oneOf options

### ISSUE THREAD

**Issue by hjhrwerv2423** [PaloAltoNetworks/docusaurus-openapi-docs#731]
Title for the GitHub issue:

"Request Not Updating When Switching Between oneOf Options"

## Describe the bug

When switching between options provided by `oneOf`, the REQUEST does not change accordingly.

## Expected behavior

Upon selecting a different object from the `oneOf` options, the REQUEST should update to reflect the chosen object's structure and values.

## Current behavior

The REQUEST fails to update according to the selected object when switching between `oneOf` options. It remains unchanged, not reflecting the new selection.

## Steps to reproduce
1. Navigate to https://docusaurus-openapi.tryingpan.dev/petstore/add-pet.
2. Switch the `petType` to either "dog" or "bee".
3. Observe in the right-hand pane that the values remain unchanged, displaying `"petType": { "huntingSkill": "adventurous" }`, which does not reflect the new selection.

## Screenshots

Please see the attached screenshot showing the issue with the REQUEST not updating after changing the `petType`.

![SCR-20240305-pldf](https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/assets/6232484/4fed8b67-c2e3-4f7e-b89b-f7f0568814cb)

## Context

This issue prevents the ability to provide JSON examples or make test requests that differ from the pet type "cat", limiting testing and documentation accuracy.

## Your Environment

Issue observed on https://docusaurus-openapi.tryingpan.dev

**Comment by sserrata** [comment]
Hi @hjhrwerv2423, unfortunately dynamically generating examples from oneOf/anyOf is not supported/planned. By default we generate only the first schema. Keep in mind that you can add your own, custom schema example/examples as needed.

**Comment by omonk** [comment]
@sserrata - hello 👋 me again :D 

Is there any reason why this isn't planned? It feels like quite an important feature.

Could you expand on adding our own "custom schema example/examples as needed", thanks!
