### ISSUE TITLE
Not able to use the plugin with Docusaurus 3.0

### ISSUE THREAD

**Issue by JaimeOVasconcelos** [PaloAltoNetworks/docusaurus-openapi-docs#753]
## Describe the bug

I have installed the plugin following the instructions, but Docusaurus 3.0 is complaining with errors.

## Expected behavior

Have the plugin working properly after installing it.

## Current behavior

Docusaurus 3.0 is raising errors and the plugin does not work.

## Steps to reproduce

Do the following: 
1. Execute `npm run start`
2. Install and configure the plugin following the instructions in the README.md (except for the line `docLayoutComponent: "@theme/DocPage"` in docusaurus.config.js that raises an error)
3. After having installed and configured the plugin, the compilation starts raising errors (see screenshot 1)
4. When I run `npm run build` it raises other errors (see screenshot 2)
 
### Screenshot 1
![Screenshot 2024-03-20 at 09 57 24](https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/assets/57861124/b22b21e0-b141-4a5b-9ab6-0f9daec00f0b)

### Screenshot 2

![Screenshot 2024-03-20 at 10 01 06](https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/assets/57861124/1c3b7baa-5ffa-4194-9c1c-e74616e697dd)

## Context

I'm trying to use the plugin to generate API documentation from an OpeanAPI spec in a yaml file.

## Your Environment

- Version used: Docusaurus 3.1.1
- Environment name and version (e.g. Chrome 59, node.js 5.4, python 3.7.3): Chrome 122.0.6261.112, Node version: v20.11.1, Python 3.9.6
- Operating System and version (desktop or mobile): Mac OS Sonoma 14.4
- Link to your project:

**Comment by tjperry07** [comment]
There is a bug when installing from npm. But I grabbed the node_modules directly from the demo, you need both folders.

https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/tree/v3.0.0-beta.6/packages

**Comment by JaimeOVasconcelos** [comment]
Thanks much @tjperry07! 
I will try it out with the specific beta version.

**Comment by JaimeOVasconcelos** [comment]
Hi @tjperry07 ,

Still doesn't work.
I have the packages installed as you can see in the package.json file:
![Screenshot 2024-03-20 at 18 50 34](https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/assets/57861124/0c0e9a09-dfd0-4451-a939-047d575c8af7)

I'm using the same configuration that is in the README.md:
![Screenshot 2024-03-20 at 18 52 12](https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/assets/57861124/66e0bb4b-406c-4d99-9907-762f4721d953)

And when I run `yarn docusaurus gen-api-docs all` it gives the following error:
![Screenshot 2024-03-20 at 18 53 34](https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/assets/57861124/b6583dbc-ce37-4e92-8daf-0fc43c59fba4)
