### ISSUE TITLE
Can change the parameter display UI to table？

### ISSUE THREAD

**Issue by lys623** [PaloAltoNetworks/docusaurus-openapi-docs#783]
source:

![image](https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/assets/4364314/5831f7f7-1bd5-46ee-9668-f231a621c83a)

to:

![image](https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/assets/4364314/18204a1d-b9db-4568-97e3-2e08eca4892e)

**Comment by sserrata** [comment]
Hi @lys623, this feature may be outside the scope of this project. Have you explored whether an open source tool exists that can convert OpenAPI to tabular and/or CSV format?
