### ISSUE TITLE
Support x-tagGroups

### ISSUE THREAD

**Issue by vl-mynick** [PaloAltoNetworks/docusaurus-openapi-docs#787]
### Is your feature request related to a problem?

I would like to have the capability for high-level grouping of API tags.
![x-tag-group 77eaaf154dd96f7967697aff1a1370c8b8fa58deb4721b1186a8829f28c5f515 5184029f](https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/assets/151511048/05dc60d9-409e-43fe-9631-cc8fedcd1dd0)

### Describe the solution you'd like

Implement support for x-tagGroups as it is done in Redocly https://redocly.com/docs/api-reference-docs/specification-extensions/x-tag-groups/

**Comment by sserrata** [comment]
Hi @vl-mynick have you had a chance to try the feature introduced here? https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/pull/737

and documented here? https://docusaurus-openapi.tryingpan.dev/sidebars#grouping-by-taggroup
