### ISSUE TITLE
 Cannot read properties of undefined (reading '1.0.0')

### ISSUE THREAD

**Issue by wade-liwei** [PaloAltoNetworks/docusaurus-openapi-docs#789]
yarn docusaurus gen-api-docs:version petstore:1.0.0 

<img width="942" alt="image" src="https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/assets/49429891/905db283-87da-425d-b0ff-0a8ce737c4f5">

**Comment by sserrata** [comment]
Hi @wade-liwei, I see the error in your screenshot but is there a particular bug you are wanting to report? If so, can you provide reproduction steps and more context?

**Comment by wade-liwei** [comment]
thanks for your reply.

I will provide the reproduction steps and more context,thanks.

**Comment by sserrata** [comment]
Hi @wade-liwei any updates? Thanks!
