### ISSUE TITLE
`error TS2688: Cannot find type definition file for 'mime'` when running the demo app

### ISSUE THREAD

**Issue by JanCizmar** [PaloAltoNetworks/docusaurus-openapi-docs#791]
## Describe the bug

I am trying to run the demo app as documented [here](https://docusaurus-openapi.tryingpan.dev/#developer-quick-start).
And I am getting following error while running the `yarn build-packages` command.
```
yarn run v1.22.17
$ lerna run build --no-private --stream
lerna notice cli v5.6.2
lerna info Executing command in 2 packages: "yarn run build"
docusaurus-plugin-openapi-docs: $ tsc
docusaurus-plugin-openapi-docs: error TS2688: Cannot find type definition file for 'mime'.
docusaurus-plugin-openapi-docs:   The file is in the program because:
docusaurus-plugin-openapi-docs:     Entry point for implicit type library 'mime'
docusaurus-plugin-openapi-docs: error Command failed with exit code 2.
docusaurus-plugin-openapi-docs: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! yarn run build exited 2 in 'docusaurus-plugin-openapi-docs'
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

## Steps to reproduce

```
git clone https://github.com/PaloAltoNetworks/docusaurus-openapi-docs.git
cd docusaurus-openapi-docs
yarn
yarn build-packages
```

- Version used: 2.1.3
- Environment name and version (e.g. Chrome 59, node.js 5.4, python 3.7.3): node v20.11.0
- Operating System and version (desktop or mobile): macOs 14.2.1

**Comment by sserrata** [comment]
Hi @JanCizmar, I'm not able to reproduce the error you're seeing, following the exact same steps. FWIW, I am on node 18 but I don't think that's the issue. Please ensure that all dependencies are installed correctly and try again.

**Comment by JanCizmar** [comment]
Hi! I've tried removing all the `node_modules` directories and `yarn.lock`, but the result is the same. However, it doesn't look like related to the other issue I have when I am trying to integrate this plugin to our project, so I am closing this.
