### ISSUE TITLE
Parameters that are defined with allOf and read-only shouldn't be displayed in the body

### ISSUE THREAD

**Issue by JaimeOVasconcelos** [PaloAltoNetworks/docusaurus-openapi-docs#807]
## Describe the bug

The parameters that go in the body of endpoints should not be present **if they are read-only**.
Currently, **this is not true** when the parameter is defined with `allOf` with `readOnly: true`. 

## Expected behavior

When the parameter is defined with `allOf`and `readOnly: true` should not be in the body.

## Current behavior

The parameters defined as `allOf` and `readOnly: true`are in the body.
See this example:
![image](https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/assets/57861124/225abdfc-ef47-4f62-9431-a6644c17928e)
Here's some of the parameters that should not be there because they are defined with `allOf` and `readOnly: true`:
<img width="291" alt="Screenshot 2024-04-20 at 16 01 11" src="https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/assets/57861124/061dd936-d89f-4633-b1ad-995351188cdd">

## Possible solution

In endpoints, if a parameter is defined with `allOf` and `readOnly: true`, they should not be in the body. 

## Steps to reproduce

1. Define an endpoint (PUT, POST, ...) with parameters in the Body and some of them are defined with `allOf` and as `readOnly: true`.
For example:
![image](https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/assets/57861124/9eb4bf0a-c01b-4dc7-a4b4-3d2eaeba76f3)
2. When generating the documentation, these parameters are included in the body of the endpoint and shouldn't.

## Your Environment

- Version used: Plugin version is 2.1.3
- Environment name and version: Chrome 123.0.6312.124, node.js 20.12.2
- Operating System and version: Mac

**Comment by sserrata** [comment]
Hi @JaimeOVasconcelos, can you try installing `0.0.0-726` to see if the issue is resolved?

**Comment by JaimeOVasconcelos** [comment]
Hey @sserrata,
I don't know if I'm going to have time to test it.
I'm closing work here to go on vacation so, I have very little time. :(

**Comment by sserrata** [comment]
Tested fix using petstore spec
