### ISSUE TITLE
Parameters that are defined as an array and read-only shouldn't be displayed in the body

### ISSUE THREAD

**Issue by JaimeOVasconcelos** [PaloAltoNetworks/docusaurus-openapi-docs#808]
## Describe the bug

The parameters that go in the body of endpoints should not be present if they are read-only.
Currently, this is not true when the parameter is defined as `type: array` and `readOnly: true`.

## Expected behavior

When the parameter is defined with `type: array` and `readOnly: true` should not be in the body.

## Current behavior

The parameters defined as `type: array` and `readOnly: true` are in the body.
For example:
<img width="254" alt="Screenshot 2024-04-20 at 16 27 18" src="https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/assets/57861124/cae80bf4-38a8-426f-8e85-2bbd97a497ee">

The result is:
![image](https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/assets/57861124/fa1f5c2d-f3a2-436a-81cd-132477550913)

## Possible solution

In the endpoints, if a parameter is defined as an `type: array` and `readOnly: true`, they should not be in the body.

## Steps to reproduce

1. Define and endpoint with a parameter that goes in the body and is defined as `type: array` and `readOnly: true`
<img width="235" alt="Screenshot 2024-04-20 at 16 31 56" src="https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/assets/57861124/6a9c05bf-2e8d-4018-9546-1527df2fed84">

2. Render the documentation with the plugin
4. The parameter appears in the body.

## Your Environment

Version used: Plugin version is 2.1.3
Environment name and version: Chrome 123.0.6312.124, node.js 20.12.2
Operating System and version: Mac

**Comment by sserrata** [comment]
Hi @JaimeOVasconcelos, can you try installing 0.0.0-726 to see if the issue is resolved?

**Comment by JaimeOVasconcelos** [comment]
Hey @sserrata,
I don't know if I'm going to have time to test it.
I'm closing work here to go on vacation so, I have very little time. :(

**Comment by sserrata** [comment]
Tested fix using petstore spec.
