### ISSUE TITLE
Save Params while navigating

### ISSUE THREAD

**Issue by ActionalyDev** [PaloAltoNetworks/docusaurus-openapi-docs#809]
### Is your feature request related to a problem?

When setting a request param, the value is removed anytime you navigate away from the page except for the Auth Bearer Token (which is saved in session storage apparently)

### Describe the solution you'd like

Is there a way to save the other parameters in session storage too so that when we navigate back to the same page they get populated from the previous input?

### Describe alternatives you've considered

It would be great also to have an option to populate the value on param with the same name on other pages. For example we have a parameter that basically gives a scope (which is not the same as the user scope) and we set this param on every api call Params.

### Additional context

We are trying to make the documentation easier to use, by not copy pasting Params constantly (with some Params never changing even among different api calls)

If there is already a way to customize that by adding some code in the config I am open to suggestions on where to start

**Comment by sserrata** [comment]
Hi @ActionalyDev, unfortunately this feature is out of scope for now. Currently we only support persisting "global" params/settings and do not yet support persisting operation/endpoint specific properties.
