### ISSUE TITLE
Unable to resolve @theme in swizzled component file

### ISSUE THREAD

**Issue by Pratosh22** [PaloAltoNetworks/docusaurus-openapi-docs#816]
## Describe the bug
Swizzled components in typescript cannot resolve "theme" components

## Expected behavior
Swizzled components should be able to resolve "theme" components

## Steps to reproduce
1.Install docusaurus-openapi-plugin and theme version "3.0.0-beta.8"
2.Run yarn swizzle 
3.Go to any file which imports file from "theme", it will be not be able to resolve

## Screenshots
<img width="1084" alt="Screenshot 2024-05-03 at 2 41 07 PM" src="https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/assets/76246084/3d3919f5-5386-44c2-aa92-f3e77cdadbaf">

## Your Environment
- Version used: 3.0.0-beta.8
- Environment name and version (e.g. Chrome 59, node.js 5.4, python 3.7.3): Nodejs v18
- Operating System and version (desktop or mobile): MacOS

**Comment by alienzhangyw** [comment]
Just add paths in your tsconfig.json
```json
{
  // This file is not used in compilation. It is here just for a nice editor experience.
  "extends": "@docusaurus/tsconfig",
  "compilerOptions": {
    "baseUrl": ".",
    "lib": [
      "ES2021",
    ],
    "jsx": "react",
    "paths": {
      "@theme/*": [
        "src/theme/*"
      ],
    }
  }
}

```

**Comment by Pratosh22** [comment]
This worked, but when i swizzle any component from APIExplorer it breaks the document and throws an error , 
<img width="1084" alt="Screenshot 2024-05-06 at 12 45 01 PM" src="https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/assets/76246084/490035ae-6ed1-4c04-a6a7-2575f27b9fdc">
It was mentioned in [#633](https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/issues/633) as well.

**Comment by alienzhangyw** [comment]
> This worked, but when i swizzle any component from APIExplorer it breaks the document and throws an error , <img alt="Screenshot 2024-05-06 at 12 45 01 PM" width="1084" src="https://private-user-images.githubusercontent.com/76246084/328113350-490035ae-6ed1-4c04-a6a7-2575f27b9fdc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5OTAzNjcsIm5iZiI6MTcxNDk5MDA2NywicGF0aCI6Ii83NjI0NjA4NC8zMjgxMTMzNTAtNDkwMDM1YWUtNmVkMS00YzA0LWE2YTctMjU3NWYyN2I5ZmRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA2VDEwMDc0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5M2FlZGZjYzU1YTA0N2I1NjFjNDk0YjhhNWQwYzBlZDllZDZhNGEyODg5ZDBkNTk1YzQ3ZTdkZWZkNjQ3ZGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.67sPZfMT0JwxBOUuEWPnctiVSZeWQJICy-H9_FRv6F8"> It was mentioned in [#633](https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/issues/633) as well.

I swizzled the ApiExplorer root directory and ApiItem directory, didn't see this error.

![image](https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/assets/58874541/caffb629-e702-47c3-b973-07bedc16db07)

If you are using yarn pnp as package manager, try to switch to `nodeLinker: node-modules`.

**Comment by Pratosh22** [comment]
Just tried the above, The error does not occur when i swizzle ApiExplorer and ApiItem Directory but it comes when i swizzle few files from ApiExplorer and do not swizzle the rest of files. Is this the expected behaviour or am i missing something? 
<img width="1705" alt="Screenshot 2024-05-06 at 4 03 39 PM" src="https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/assets/76246084/3cf3660c-bed2-452b-807a-af9aa548a8a5">
The below are the files i swizzled
<img width="427" alt="Screenshot 2024-05-06 at 4 04 18 PM" src="https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/assets/76246084/248acb59-9552-4f84-8d79-6a7e6c8bbcd5">

**Comment by alienzhangyw** [comment]
> Just tried the above, The error does not occur when i swizzle ApiExplorer and ApiItem Directory but it comes when i swizzle few files from ApiExplorer and do not swizzle the rest of files. Is this the expected behaviour or am i missing something? <img alt="Screenshot 2024-05-06 at 4 03 39 PM" width="1705" src="https://private-user-images.githubusercontent.com/76246084/328150549-3cf3660c-bed2-452b-807a-af9aa548a8a5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwNzEzNTksIm5iZiI6MTcxNTA3MTA1OSwicGF0aCI6Ii83NjI0NjA4NC8zMjgxNTA1NDktM2NmMzY2MGMtYmVkMi00NTJiLTgwN2EtYWY5YWE1NDhhOGE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA3VDA4MzczOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI3ZDhiYjUxNWFjM2NmYTI0MTc4YjgzMjM3YzIxODUwMmFkYTViMjY4MzFmNDJkNzE5OWI2ZGRjMWYwYjI1ZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qZ-pK4bAI8Zo2PuosT-RO7GsQy8JjAjqpqy5noRRSsM"> The below are the files i swizzled <img alt="Screenshot 2024-05-06 at 4 04 18 PM" width="427" src="https://private-user-images.githubusercontent.com/76246084/328150594-248acb59-9552-4f84-8d79-6a7e6c8bbcd5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwNzEzNTksIm5iZiI6MTcxNTA3MTA1OSwicGF0aCI6Ii83NjI0NjA4NC8zMjgxNTA1OTQtMjQ4YWNiNTktOTU1Mi00Zjg0LThkNzktNmE3ZTZjOGJiY2Q1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA3VDA4MzczOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxZTk0NGExMzBkN2JhYzAyMjU3MDg0OTUwY2E2N2QxNDM2NTQxMDllZWI4Y2JiN2RmNWUxMmMyYmQzZDA1ZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VQmPhDx4Bgfh1-CVWzOCw1p6PamhIXvHKmFTEYfoww4">

Yes, you need many other files because ParamFormItems uses a FormItem component, and a reat-hook-form context provided in Response component. Basicly you need to swizzle all related files to make it work.
