### ISSUE TITLE
Changes to swizzled ApiExplorer/SecuritySchemes do not take effect.

### ISSUE THREAD

**Issue by tyler-mairose-sp** [PaloAltoNetworks/docusaurus-openapi-docs#824]
## Describe the bug

When I swizzle (eject) ApiExplorer/SecuritySchemes, the changes I make to the index.js file do not take effect.

To keep things simple I wanted to expand the Security Schemes section by default. To accomplish this I was changing line 24 to set open to true:

`{ className: "openapi-security__details", open: true }`

## Expected behavior

I would expect that the dropdown here would be expanded when I open the page.

<img width="1301" alt="image" src="https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/assets/84410962/270aa55a-b452-428d-b6ba-98964b0506e0">

## Current behavior

Right now nothing happens when I change this value or anything else on the swizzled component.

<img width="1332" alt="image" src="https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/assets/84410962/59636a81-ac7d-4372-9c64-1d84deac74b6">

## Context

Our users don't necessarily know that that AUTHORIZATION: OAUTH can be expanded. Adding an arrow to show that this section could be expanded and closed. The section is a little cluttered for us and we wanted to remove some of the extra properties description and flows. We also wanted to add a custom variable in our spec and read it in and show it in this section as well.

## Your Environment

- Version used:
- Docusaurus Version: 2.4.3
- docusaurus-theme-openapi-docs version: 2.0.2
- Environment name and version (e.g. Chrome 59, node.js 5.4, python 3.7.3): Chrome Version 124.0.6367.203
- Operating System and version (desktop or mobile): MacOS 14.5 (23F79)
- Link to your project: https://github.com/sailpoint-oss/developer.sailpoint.com

**Comment by sserrata** [comment]
Hi @tyler-mairose-sp, you'd have to swizzle the entire `ApiExplorer` component for the override to work. Heads up that you may need to change an import statement for `MethodEndpoint` from `"../../ApiItem/hooks"` to `"@theme/ApiItem/hooks"`

**Comment by sserrata** [comment]
Will update docs coinciding with next stable v2/v3 release

**Comment by tyler-mairose-sp** [comment]
@sserrata That worked. I also had to install the `react-live` package to get it to work. That issue was coming from `ApiExplorer/LiveEditor/index.js`

Thank you!
