### ISSUE TITLE
Make the request timeout a configurable setting

### ISSUE THREAD

**Issue by drwelby** [PaloAltoNetworks/docusaurus-openapi-docs#833]
We found that certain requests were, according to the browser's dev tools, returning responses, but the API Explorer's Response section would not update with the request content.

Poking around, the request to the API is set with a timeout of 5000ms here https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/blob/v3.0.0/packages/docusaurus-theme-openapi-docs/src/theme/ApiExplorer/Request/makeRequest.ts#L14 and the requests that weren't rendering responses had response times over 5 seconds.

So it appears the UI is giving up rendering the response even though the fetch eventually works.

For those of us with slow APIs it would be useful to have a config setting where we can override the timeout to a larger value.

**Comment by sserrata** [comment]
Hi @drwelby, it should be possible to override the timeout by swizzling `Request/makeRequest`:

![Screenshot 2024-06-18 at 11 12 58 AM](https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/assets/9343811/357b1c97-ab85-488f-9929-fe80424dd198)

**Comment by drwelby** [comment]
Of course! I totally forgot about swizzling!

I tried (patch-package)[https://github.com/ds300/patch-package] which also works, but swizzles are even better.

**Comment by drwelby** [comment]
@sserrata I just tried it, and I didn't see the change - does Swizzling only work at the component level maybe?

**Comment by moono** [comment]
Thanks @sserrata and @drwelby this was exactly what I was looking for...

**Comment by jeelsha** [comment]
Hello @sserrata @drwelby 
we are facing same issue. But we are not able to resolve this. 

we have tried 
 npx docusaurus swizzle docusaurus-theme-openapi-docs ApiExplorer/Request --eject

can you please let me know how you have solved it?

this is 

 plugins: [
    [
      "docusaurus-plugin-openapi-docs",
      {
        id: "api",
        docsPluginId: "classic",
        config: {
          v1: {
            specPath: "static/json/openapi.json", // Path for version 1.0 OpenAPI spec
            outputDir: "docs/api/v1", // Output directory for version 1.0
            sidebarOptions: {
              groupPathsBy: "tag",
            },
          },
          v2: {
            specPath: "static/json/openapiv2.json", // Path for version 2.0 OpenAPI spec
            outputDir: "docs/api/v2", // Output directory for version 2.0
            sidebarOptions: {
              groupPathsBy: "tag",
            },
          },
        },
      },
    ],
  ],

**Comment by drwelby** [comment]
> we have tried
> npx docusaurus swizzle docusaurus-theme-openapi-docs ApiExplorer/Request --eject

Did you then go to `/src/theme/ApiDemoPanel/Request/makeRequest.js` and edit the timeout value in `fetchWithtimeout()`?

**Comment by bimusiek** [comment]
I understand that swizzling is one of the ways to go, but thats is unusual solution for a problem that could be solved by adding timeout parameter to configuration. 👎
