### ISSUE TITLE
Download URL on versions is referring to the main version

### ISSUE THREAD

**Issue by ahelmy** [PaloAltoNetworks/docusaurus-openapi-docs#855]
## Describe the bug

The export button that downloads the OpenAPI spec on the version switch refers to the main version `downloadUrl` property.

## Expected behavior

Should download the version URL.

## Current behavior

Download the main version URL

## Possible solution

A `downloadUrl` property to be added in `versions` section.

## Steps to reproduce

1. Add a version to `versions` section.
2. Add `downloadUrl` to main version.
3. Click export and check the URL.

## Your Environment

- Docusaurus = 3.3.2
- docusaurus-plugin-openapi-docs = 3.0.0-beta.10

**Comment by sserrata** [comment]
Hi @ahelmy, thanks for reporting this issue. If you're up to it, we're happy to accept a PR to address to this issue.
