### ISSUE TITLE
Change endpoints ServerUrl location to be table

### ISSUE THREAD

**Issue by ahelmy** [PaloAltoNetworks/docusaurus-openapi-docs#879]
### Is your feature request related to a problem?

It is related to UI/UX to show the server URLs in a table shown on every endpoint below the request path.

### Describe the solution you'd like

To add a table in the green area:
| Server Name          | URL     | 
| ------------- | -------- | 
| `Production`    |  https://petstore.swagger.io | 
| `Pre Production`    |  https://petstore.pre.swagger.io |

And just show the request path to be `/sandbox/pet `
<img width="968" alt="Screenshot 2024-07-05 at 11 37 03 AM" src="https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/assets/7501254/fbf0102c-8178-4f72-8306-e6ead7c02d65">

### Describe alternatives you've considered

N/A

### Additional context

It could be enabled by a flag.

**Comment by sserrata** [comment]
Hi @ahelmy, this should already be possible using the operation `description`, which supports markdown. FWIW, I've also seen other API doc writers create a dedicated doc for server URLs. 

If that doesn't work for you, have you explored using a custom mustache template to inject the table?

**Comment by sserrata** [comment]
This technically works, but bummer that there isn't a way to inject the list below the `MethodEndpoint` component:

<img width="1876" alt="Screenshot 2024-09-10 at 1 42 52 PM" src="https://github.com/user-attachments/assets/ef90e854-cc7b-44f5-8e71-349b40cfb2cf">

```
---
id: {{{id}}}
title: "{{{title}}}"
description: "{{{frontMatter.description}}}"
{{^api}}
sidebar_label: Introduction
{{/api}}
{{#api}}
sidebar_label: "{{{title}}}"
{{/api}}
{{^api}}
sidebar_position: 0
{{/api}}
hide_title: true
{{#api}}
hide_table_of_contents: true
{{/api}}
{{#json}}
api: {{{json}}}
{{/json}}
{{#api.method}}
sidebar_class_name: "{{{api.method}}} api-method"
{{/api.method}}
{{#infoPath}}
info_path: {{{infoPath}}}
{{/infoPath}}
custom_edit_url: null
{{#frontMatter.proxy}}
proxy: {{{frontMatter.proxy}}}
{{/frontMatter.proxy}}
{{#frontMatter.hide_send_button}}
hide_send_button: true
{{/frontMatter.hide_send_button}}
{{#frontMatter.show_extensions}}
show_extensions: true
{{/frontMatter.show_extensions}}
---

<ul>
  {{#api.servers}}
  <li>{{url}}</li>
  {{/api.servers}}
</ul>

{{{markdown}}}
```

That said, you may want to explore building your own `markdownGenerator` function, which is one of our more obscure features: https://docusaurus-openapi.tryingpan.dev/#:~:text=of%20supported%20options.-,markdownGenerators,-object

I'm going to experiment a bit and check back if I come up with something.

**Comment by sserrata** [comment]
Ah, turns out the `markdownGenerators` option may be the way to go here.

<img width="1869" alt="Screenshot 2024-09-10 at 3 08 15 PM" src="https://github.com/user-attachments/assets/61a2fbc5-2786-4854-abb9-cdb102e8c5eb">

Here's how I did it...

Created these functions in my docusaurus.config.ts:

```
function createServersTable(servers: any[]) {
  if (servers.length) {
    return `| Server | URL |
| ---- | ----- |
${servers
  .map((server) => {
    return `| ${server.url} | ${server.description} | `.replace("\n", "<br/>");
  })
  .join("\n")}
    `;
  }
}

export function myCustomApiMdGenerator({
  title,
  api: {
    deprecated,
    "x-deprecated-description": deprecatedDescription,
    description,
    method,
    path,
    extensions,
    parameters,
    requestBody,
    responses,
    callbacks,
    servers, // destructure servers here
  },
  infoPath,
  frontMatter,
}: ApiPageMetadata) {
  return render([
    `import ApiTabs from "@theme/ApiTabs";\n`,
    `import DiscriminatorTabs from "@theme/DiscriminatorTabs";\n`,
    `import MethodEndpoint from "@theme/ApiExplorer/MethodEndpoint";\n`,
    `import SecuritySchemes from "@theme/ApiExplorer/SecuritySchemes";\n`,
    `import MimeTabs from "@theme/MimeTabs";\n`,
    `import ParamsItem from "@theme/ParamsItem";\n`,
    `import ResponseSamples from "@theme/ResponseSamples";\n`,
    `import SchemaItem from "@theme/SchemaItem";\n`,
    `import SchemaTabs from "@theme/SchemaTabs";\n`,
    `import Heading from "@theme/Heading";\n`,
    `import OperationTabs from "@theme/OperationTabs";\n`,
    `import TabItem from "@theme/TabItem";\n\n`,
    createHeading(title),
    createMethodEndpoint(method, path),
    createServersTable(servers),
    infoPath && createAuthorization(infoPath),
    frontMatter.show_extensions
      ? createVendorExtensions(extensions)
      : undefined,
    createDeprecationNotice({ deprecated, description: deprecatedDescription }),
    createDescription(description),
    requestBody || parameters ? createRequestHeader("Request") : undefined,
    createParamsDetails({ parameters, type: "path" }),
    createParamsDetails({ parameters, type: "query" }),
    createParamsDetails({ parameters, type: "header" }),
    createParamsDetails({ parameters, type: "cookie" }),
    createRequestBodyDetails({
      title: "Body",
      body: requestBody,
    } as RequestBodyProps),
    createStatusCodes({ responses }),
    createCallbacks({ callbacks }),
  ]);
}
```

Then passed the custom markdown generator via my `docusaurus-plugin-openapi-docs` config:

```
          petstore: {
            specPath: "examples/petstore.yaml",
            proxy: "https://cors.pan.dev",
            outputDir: "docs/petstore",
            sidebarOptions: {
              groupPathsBy: "tag",
              categoryLinkSource: "tag",
            },
            downloadUrl: "/petstore.yaml",
            hideSendButton: false,
            showSchemas: true,
            markdownGenerators: { createApiPageMD: myCustomApiMdGenerator },
          } satisfies OpenApiPlugin.Options,
```

**Comment by sserrata** [comment]
Whoops, I meant my column labels to be "URL" and "Description", but you get the idea.

**Comment by ahelmy** [comment]
Many thanks @sserrata , you really made it 💪

**Comment by sserrata** [comment]
Thank you for bringing this issue! You helped highlight a need to improve the docs around this particular feature, especially since it unlocks so many possibilities for customizing the output.
