### ISSUE TITLE
Response example summary is broken in v3

### ISSUE THREAD

**Issue by IanVS** [PaloAltoNetworks/docusaurus-openapi-docs#882]
## Describe the bug

I am upgrading from 2.0 beta to 3.0.1, and get several of these errors when I build:

```
[react-markdown] Warning: please pass a string as `children` (not: `[object Object]`)
```

I narrowed this down to the use of response example summaries, which worked previously.

## Expected behavior

I assume I should be able to continue to provide response example summaries.

## Current behavior

```
[react-markdown] Warning: please pass a string as `children` (not: `[object Object]`)
```

And the summary does not get rendered

## Steps to reproduce

1. In the petstore demo, add a response example summary, e.g. to `/users/login.get.responses."200".content.application/json.examples.response` (line 900 right now)
2. `summary: this breaks`
3. clean api docs and build the demo, you'll see a warning when building, and if you visit the page, you won't see the summary and will see a console warning

## Context

I have some response examples for certain parameters, e.g.:

```
            includeCounts:
              summary: Metadata returned when including request params for <code>includeCounts=true</code>, <code>pageSize=1</code>, and <code>cursor="somevalue"</code>.
```

These are now broken and do not appear in the built results.  I tried simplifying this down to just straight text, and it also fails, though at first I thought it was related to the jsx.

I simplified things and logged out what `react-markdown` was getting as `children`, and it was this:

<img width="587" alt="image" src="https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/assets/4616705/004efae7-c812-4cdd-bbe5-3d8ffcca0b26">

**Comment by sserrata** [comment]
Hi @IanVS, on first inspection the issue seems to stem from the `Markdown` theme component - it doesn't appear to render anything in the DOM despite showing up in the generated MDX output.

**Comment by IanVS** [comment]
When I was looking into it, I did a search for the places that `react-markdown` is used in the plugin, and most places stringify the children, but I think it was the `Markdown` component that didn't.  From what I could tell, it looked like a `React.Element` was being provided to `react-markdown`, when it only wanted a string.

**Comment by sserrata** [comment]
Turns out I was using the `Markdown` component incorrectly, or at least I should have chosen a different prop variable from `children` which is reserved by the `create` function. This works:

```
                </TabItem><TabItem
                  label={"response"}
                  value={"response"}
                >
                  <Markdown
                    markdown={"This breaks"}
                  >
                    
                  </Markdown><ResponseSamples
                    responseExample={"OK"}
                    language={"json"}
                  >
                    
                  </ResponseSamples>
                </TabItem>
```

**Comment by sserrata** [comment]
Actually, the more I look into it, seems we don't need the `Markdown` component (anymore?). Docusaurus v3 appears to render markdown just fine, even if it's inside a `div`. Seems safe to just replace `Markdown` with `div` - I'll open a PR.
