### ISSUE TITLE
Show description of 'oneOf' schema items

### ISSUE THREAD

**Issue by IanVS** [PaloAltoNetworks/docusaurus-openapi-docs#887]
### Is your feature request related to a problem?

I have an endpoint like `/command` which takes a request body like:

```
{
	command: 'StreamLogs"
	args: {}
}
```

I'd like to use `oneOf` to describe the different kinds of commands that can be sent, and it would be really helpful to have a `description` for each one that could appear between the choice buttons/tabs and the schema itself.

### Describe the solution you'd like

I'd like for a `description` provided inside a `oneOf` schema to appear below the tabs used to pick between the schemas.

### Describe alternatives you've considered

I can add the description to the `command` property, for now.

**Comment by sserrata** [comment]
Hi @IanVS, I think this is what you have in mind?

https://github.com/user-attachments/assets/650e5deb-11ef-4f66-8a29-cb6868486088

It's fairly easy to support but now I am noticing that the "type only" schemas don't necessarily jive with schemas that render in the tree.

**Comment by IanVS** [comment]
Yes that's exactly what I was thinking of.  In my specific case, I will have full schemas.  But you're right, the type-only ones do look a bit out-of-place there.

**Comment by IanVS** [comment]
I think that issue isn't directly related to this feature request though, right?  Just another thing you noticed while taking a look at this?
