### ISSUE TITLE
[FR] index pages for individual tags

### ISSUE THREAD

**Issue by matoous** [PaloAltoNetworks/docusaurus-openapi-docs#90]
### Is your feature request related to a problem?

If operations are grouped by tags (`groupPathsBy: 'tags'` option) the operations are correctly grouped under individual tags but even if the tag has description it is nowhere to be found.

### Describe the solution you'd like

It would be perfect if the tag description could be used to generate index pages for individual tags.

### Describe alternatives you've considered

The pages can be created manually if necessary such as this page: https://docusaurus-openapi.tryingpan.dev/api/food/burgers/introduction in the demo.

### Additional context

Happy to try and contribute if someone would please point me in the right directions 🙏

**Comment by sserrata** [comment]
Thanks for the FR @matoous! We can certainly take a look to see if this is possible and would definitely appreciate a contribution.

**Comment by matoous** [comment]
@sserrata I see this new commit made it's way to `main`: https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/commit/e17c515ec0cc0ca1b99e1b3a6e193204b1b78a5e, is it related to this?

**Comment by sserrata** [comment]
Hi @matoous, yes, but it needs a little more work before it's ready. The idea will be to allow users to select whether they want to use "tag" descriptions or "info" as the "index" page for categories. The default will be "tag" descriptions when grouping paths by tag.

**Comment by sserrata** [comment]
Hi @matoous, the changes have been merged and can be tested using canary release [0.0.0-355](https://www.npmjs.com/package/docusaurus-plugin-openapi-docs/v/0.0.0-355). Be sure to also upgrade the theme.

Please see the `README.md` for usage or just adapt this example:

```javascript
petstore: {
  specPath: "examples/petstore.yaml",
  outputDir: "api/petstore",
  sidebarOptions: {
    groupPathsBy: "tags",
    categoryLinkSource: "tag",
  },
},
```

Interested in your feedback on the end result and usage. Thanks!

**Comment by matoous** [comment]
@sserrata just gave it a try, exactly what we were looking for! Awesome, thanks a lot 🙏
