### ISSUE TITLE
Unable to install with rush/pnpm due to upstream dependency bug

### ISSUE THREAD

**Issue by robbieaverill** [PaloAltoNetworks/docusaurus-openapi-docs#905]
## Describe the bug

When I try to install this package into a Docusaurus site that uses rush/pnpm as the package manager, I am unable to.

This is causes by an upstream bug in postman-code-generators: https://github.com/postmanlabs/postman-code-generators/issues/760. I'm raising it here in case others are experiencing the same issue, but also in case there's a solution to avoid the issue in this package.

I don't actually want any generated code examples at all. It's a shame that I can't use this package without them.

## Expected behavior

I should be able to install the package.

## Current behavior

```
$ pnpm install

...
node_modules/.pnpm/postman-code-generators@1.12.0/node_modules/postman-code-generators: Running postinstanode_modules/.pnpm/postman-code-generators@1.12.0/node_modules/postman-code-generators: Running postinstall script, failed in 920ms
.../node_modules/postman-code-generators postinstall$ node npm/deepinstall.js
│ Detected package manager: pnpm
│ Running pre-package script
│ Run successful languages.js saved in lib/assets
│ csharp-httpclient: pnpm install --no-audit --production
│ Failed to run pnpm install on codegen csharp-httpclient, here is the error:
│ csharp-restsharp: pnpm install --no-audit --production
│ Failed to run pnpm install on codegen csharp-restsharp, here is the error:
│ .../common/temp/node_modules/.pnpm/async@3.2.2/node_modules/a…
│             if (fn === null) throw new Error("Callback was already called.");
│                                    ^
│ Error: Callback was already called.
│     at .../common/temp/node_modules/.pnpm/async@3.2.2/node_mo…
│     at .../common/temp/node_modules/.pnpm/async@3.2.2/node_mo…
│     at .../common/temp/node_modules/.pnpm/postman-code-genera…
│     at Array.forEach (<anonymous>)
│     at .../common/temp/node_modules/.pnpm/postman-code-genera…
│     at .../common/temp/node_modules/.pnpm/async@3.2.2/node_mo…
│     at replenish (.../common/temp/node_modules/.pnpm/async@3.…
│     at iterateeCallback (.../common/temp/node_modules/.pnpm/a…
│     at .../common/temp/node_modules/.pnpm/async@3.2.2/node_mo…
│     at .../common/temp/node_modules/.pnpm/async@3.2.2/node_mo…
│ Node.js v20.11.0
└─ Failed in 921ms at .../common/temp/node_modules/.pnpm/postman-code-generators@1.12.0/node_modules/postman-code-generators
 ELIFECYCLE  Command failed with exit code 1.
```

## Possible solution

Make the code-generators package opt-in.

## Your Environment

- Version used: 3.0.1
- Environment name and version: Node 20.11.0
- Operating System and version (desktop or mobile): Mac M1

**Comment by lpicchi** [comment]
Workaround till they fix this:

```json
  "resolutions": {
    "postman-code-generators": "1.10.1"
  },
```

**Comment by robbieaverill** [comment]
Thanks @lpicchi. I have 1.12.0 installed - is a downgrade necessary?

**Comment by lpicchi** [comment]
@robbieaverill I don't have any knowledge on rush.js but according to their docs it supports a "globalOverrides" config. You should use it to set the package to the mentioned "safe" version.

https://rushjs.io/pages/configs/pnpm-config_json/

**Comment by robbieaverill** [comment]
Using version 1.10.1 will not work entirely for Rush/pnpm users, because prior to 1.11.0 postman-code-generators was not using your package manager when performing deep installs. See https://github.com/postmanlabs/postman-code-generators/pull/744.

It might work for users without private NPM tokens, or those using npm directly.

**Comment by lpicchi** [comment]
I'm sorry to hear that... it seems there is no workaround for your use case then

**Comment by robbieaverill** [comment]
After trying again, I can confirm that 1.10.1 installs locally without this error. Unfortunately, another issue presents. The dependency's deep-install process tries to install using the wrong package manager, which doesn't share the same auth as my Rush setup. This was fixed in https://github.com/postmanlabs/postman-code-generators/pull/744, but the combination of both bugs still makes this dependency unusable in this context.

**Comment by robbieaverill** [comment]
In case it is useful to anyone, when using Rush and finding build errors due to NPM repository authorization issues in CI (when deep installing postman-code-generators), I did the following as a workaround:
* Accept that I don't want or need the code snippets and I am happy to remove them
* Replace `postman-code-generators` with an empty package using [`globalOverrides`](https://rushjs.io/pages/configs/pnpm-config_json) to force install of a local, stub library
  * Example is configured as `libraries/temp/postman-code-generators` with a stub package.json and other necessary files
* Swizzle the `ApiExplorer/index` file into my project
* Remove the `CodeSnippets` component from it, which appears to be the only place referencing postman-code-generators

Swizzled file:
```jsx
# File: src/theme/ApiExplorer/index.jsx
import React from 'react';
import Request from '@theme/ApiExplorer/Request';
import Response from '@theme/ApiExplorer/Response';

export default ({ item }) => (
    <>
        <Request item={item} />
        <Response item={item} />
    </>
);
```

Note that I had a hard time getting TypeScript configuration to appreciate this new file. I raised an issue for that as #920 and proceeded to swizzle it as a JavaScript file instead.

**Comment by robbieaverill** [comment]
This should be fixed by updating `postman-code-generators` to v1.13.0 or newer.
