### ISSUE TITLE
Header parameter into code example

### ISSUE THREAD

**Issue by emilleszczak2** [PaloAltoNetworks/docusaurus-openapi-docs#906]
## Documentation link

no available yet

## Describe the problem

Is it possible to attach the Header parameter value (ex. -H 'Signature: <SIGNATURE_VALUE>') or compute it in the code example?
![Screenshot 2024-08-06 at 11 52 03](https://github.com/user-attachments/assets/9cc004ac-c70a-4931-8e01-42414c4cc6be)

**Comment by sserrata** [comment]
FYI, the param requires a value for it to appear in a code snippet:

<img width="1318" alt="Screenshot 2024-08-06 at 12 21 15 PM" src="https://github.com/user-attachments/assets/217ccacd-226a-4377-83f0-0b7f09daba3c">

**Comment by emilleszczak2** [comment]
@sserrata is it a way to complete it with default value?
