### ISSUE TITLE
Searching for endpoint parameters does not work

### ISSUE THREAD

**Issue by jaimevasco69** [PaloAltoNetworks/docusaurus-openapi-docs#936]
## Describe the bug

When searching (with Algolia) for a specific endpoint parameter in Docusaurus, no results are shown with the exact match of the parameter. The closest matches found are through the parameter's description.

This may be due to the endpoint parameters being created with a `<span>` tag (unlike the description that is in a `<p>` tag), and Docusaurus ignores the parameter name when it sends the information to Algolia.

This is very important because users search for specific parameters in the endpoints.

## Expected behavior

When searching for a specific endpoint parameter, you should have at least an exact match in the results.

## Current behavior

There is no exact match in the results when searching for an endpoint parameter. 

## Possible solution

Maybe put the endpoint parameters inside a `<p>` tag.

## Steps to reproduce

You can test it at https://developers.probely.com

1. Go to the Search box
2. Type "check_fullpath"

You will get a single result, but the match is done through the parameter description, when it should be throught the parameter name.

In Algolia's search tools, I can see that the information it got from Docusaurus no parameters' names, just their descriptions.

![image](https://github.com/user-attachments/assets/73259ad5-677a-48e7-9c33-0469eb006826)

## Context

This is very important because developers search for specific parameters they know. 
Since the parameter names are not being taken into account (due to the way they are being rendered on the page), the search results will be poor. 

## Your Environment

- Version used: Docusaurus 2.4.3, OpenAPI Docs 2.1.0 
- Environment name and version Chrome 127.0.6533.120
- Operating System and version (desktop or mobile): MaxOS

**Comment by sserrata** [comment]
Hi @jaimevasco69, the property names are currently wrapped in a `strong` tag. For now, you should be able to update your Algolia crawler config to include this tag/selector at the preferred hierarchy.

For the future, If we can safely assume _most_ Docusaurus+Algolia users stick with the default crawler config (or copy Docusaurus' website crawler config) then we can explore switching to a `p` tag.

**Comment by jaimevasco69** [comment]
Hey @sserrata ,

Managed to configure the index in Algolia.
Added "article span strong" to the content searchable attribute. Works fine.
Thanks!
You should add this somewhere in the plugin documentation. ;)
