### ISSUE TITLE
useScrollController called outside of ScrollControllerProvider in yarn PnP mode

### ISSUE THREAD

**Issue by smeng9** [PaloAltoNetworks/docusaurus-openapi-docs#947]
## Describe the bug

Building the Template Repository project throws useScrollController called outside of ScrollControllerProvider

## Expected behavior

The Template Repository should be built without a problem.

## Current behavior

I can't build the Template Repository in my project setup.

## Possible solution

I guess it is some dependency issue but not sure.

## Steps to reproduce

1. `git clone https://github.com/PaloAltoNetworks/docusaurus-template-openapi-docs`
2. `cd docusaurus-template-openapi-docs && yarn set version berry` and set yarn to PnP mode by `rm .yarnrc.yml` or just change .yarnrc.yml's nodeLinker to pnp
3. `yarn install` then add missing dependencies `yarn add @docusaurus/theme-common @docusaurus/plugin-content-docs`
4. `yarn docusaurus gen-api-docs all && yarn build`

## Screenshots

<img width="566" alt="Screenshot 2024-09-05 at 1 31 58 PM" src="https://github.com/user-attachments/assets/f8466e86-0cdb-4aff-a0db-c67ef1d10de1">

## Context

I am not able to build the project using yarn PnP mode.
I can still build the project using nodeLinker: node-modules in .yarnrc.yml .
However that will take more space to store the package dependencies during development and CI release.

## Your Environment

- Version used: Docusaurus OpenAPI Docs 4.0.1, Docusaurus 3.5.2
- Environment name and version (e.g. Chrome 59, node.js 5.4, python 3.7.3): Safari 17.5, node.js 20.10.0, yarn 4.4.1
- Operating System and version (desktop or mobile): desktop macOS Sonoma 14.5
- Link to your project: https://github.com/PaloAltoNetworks/docusaurus-template-openapi-docs

**Comment by sserrata** [comment]
Hi @smeng9, I don't use pnp so not too familiar with the issue you're encountering. That said, I removed the `yarn.lock` file from the template just in case it was causing any conflicts.

**Comment by smeng9** [comment]
Fixed after https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/pull/1019
