### ISSUE TITLE
Default values are not rendered in the generated reference documentation

### ISSUE THREAD

**Issue by jaimevasco69** [PaloAltoNetworks/docusaurus-openapi-docs#955]
## Describe the bug

The default value is not displayed in this new version of the plugin for Docusaurus 3.5.2.
It was working in version 2.X.
 
## Expected behavior

When a parameter as a default value specified, that should appear in the generated documentation. 
It happened in version 2.X, as you can see in the following picture:

<img width="980" alt="image" src="https://github.com/user-attachments/assets/fcd085ac-c861-4375-9ce6-d72797cb3009">

## Current behavior

Parameters with default values specified don't have that indicated in the generated documentation. 
This does not happen in your latest version (4.0.1), as you can see in the following picture:

<img width="958" alt="image" src="https://github.com/user-attachments/assets/86658734-3390-424e-8ef4-2632f996f725">

## Steps to reproduce

You can [download here](https://developers.probely.com/api/reference/probely-developer-documentation) the openapi.yaml  and generate the reference documentation.

## Your Environment

- Version used: **Docusaurus**: 3.5.2, **OpenAPI Docs**: 4.0.1
- Environment name and version: **Chrome** Version 128.0.6613.120 (Official Build) (arm64), **node.js** v20.11.1, **python** 3.9.6
- Operating System and version (desktop or mobile): MacOS

**Comment by sserrata** [comment]
Seems to be an edge case where, if the `default` value is a `boolean` and is also `false`, the `guard` utility fails to render. Also, since we're using `ReactMarkdown` to render default values, any characters that would otherwise be recognized as markdown must be escaped, such as `[]`.
