### ISSUE TITLE
Authorization information disappeared in version 4.0.1 

### ISSUE THREAD

**Issue by jaimevasco69** [PaloAltoNetworks/docusaurus-openapi-docs#956]
## Describe the bug

Authorization information that was displayed in version 2.X disappeared in version 4.0.1

## Expected behavior

The authorization info should be displayed as it was in version 2.X

<img width="1179" alt="image" src="https://github.com/user-attachments/assets/85b1115d-408a-4f16-aa36-5faab9d4d6df">

## Current behavior

Authorization info disappeared 

<img width="1176" alt="Screenshot 2024-09-10 at 12 20 18" src="https://github.com/user-attachments/assets/98f64bb4-5ccb-4415-89cc-be31b4cd2bdf">

## Steps to reproduce

You can [download here](https://developers.probely.com/api/reference/probely-developer-documentation) my OpenAPI spec to test it.

## Your Environment

Version used: **Docusaurus**: 3.5.2, **OpenAPI Docs**: 4.0.1
Environment name and version: **Chrome** Version 128.0.6613.120 (Official Build) (arm64), **node.js** v20.11.1, **python** 3.9.6
Operating System and version (desktop or mobile): **MacOS**

**Comment by sserrata** [comment]
Addressed in #957
