### ISSUE TITLE
[FR] Execute query from docs page

### ISSUE THREAD

**Issue by yongwee** [PaloAltoNetworks/docusaurus-openapi-docs#99]
### Is your feature request related to a problem?

No way to execute queries from docs page right now since Execute button has been removed.

Noticed that Execute button for executing queries directly from the docs page used to be there but was removed from v18.0.0 onwards.

### Describe the solution you'd like

Bring back the query execution capability.

### Describe alternatives you've considered

Right now I'm falling back to another older plugin of yours https://github.com/cloud-annotations/docusaurus-openapi
But this project's approach of generating mdx docs from Swagger is much more flexible since I can easily add additional md files for supplementary information and I'd like to switch to this. But the removal of the feature makes it a very difficult sell since my boss explicitly wants it :(

### Additional context

Users benefit greatly from being able to run queries from docs page rather than have to download Postman or use curl

![Screenshot_2022-05-23_at_10_10_40_AM](https://user-images.githubusercontent.com/7090189/169731037-d085eea5-6e61-4440-b4f4-fccde9a11184.png)

**Comment by sserrata** [comment]
Hi @yongwee, we intentionally removed this option since it poses a security risk by allowing the storage of API keys/tokens in the browser.

**Comment by stephen-spiny** [comment]
> Hi @yongwee, we intentionally removed this option since it poses a security risk by allowing the storage of API keys/tokens in the browser. We can revisit adding it back if we can arrive at a way to safely handle credentials. One idea would be to support callbacks for storing/reading credentials and making API requests. This would allow the developer to select how they want to handle secrets storage/retrieval and how to perform API requests (i.e. via a backend).

I believe this would be a great feature to add and the solution @sserrata suggested seems ideal. 

We have an app that users login to on the same top level domain as our docs. Simply having the capability to "execute" would suffice as we read tokens from a cookie on the top level domain for authentication. Additionally adding a raw auth input with no persistence(similar to the [old plugin](https://github.com/cloud-annotations/docusaurus-openapi)) would also work, albeit a bit more work for the end user, as a manner to circumvent the security risks posed by storing keys/tokens in the browser.

This feature would add parity of features you find in other sophisticated API explorer solutions.

**Comment by yongwee** [comment]
Actually yea I concur, the callback way (for storing/retrieving credentials and also transport) seems like the long-term way to do things, and a simple "fix" of ridding the persistence is sufficient short-term (and is probably good enough for most cases).

For now I have actually swizzled the component to add the execute button back in lol, but would really be awesome if swizzling isn't required!
